// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/shipping-profiles": {
    params: {};
  };
  "/api/webhooks/workflow": {
    params: {};
  };
  "/auth-providers": {
    params: {};
  };
  "/notifications": {
    params: {};
  };
  "/integrations": {
    params: {};
  };
  "/auth/session-token": {
    params: {};
  };
  "/collections": {
    params: {};
  };
  "/time-slots": {
    params: {};
  };
  "/analytics": {
    params: {};
  };
  "/auth/exit-iframe": {
    params: {};
  };
  "/billing/invoices": {
    params: {};
  };
  "/campaigns": {
    params: {};
  };
  "/customers": {
    params: {};
  };
  "/inventory": {
    params: {};
  };
  "/locations": {
    params: {};
  };
  "/shipments": {
    params: {};
  };
  "/templates": {
    params: {};
  };
  "/activity": {
    params: {};
  };
  "/calendar": {
    params: {};
  };
  "/payments": {
    params: {};
  };
  "/settings": {
    params: {};
  };
  "/billing": {
    params: {};
  };
  "/drivers": {
    params: {};
  };
  "/support": {
    params: {};
  };
  "/auth/callback": {
    params: {};
  };
  "/campaigns/:id": {
    params: {
      "id": string;
    };
  };
  "/customers/:id": {
    params: {
      "id": string;
    };
  };
  "/inventory/:id": {
    params: {
      "id": string;
    };
  };
  "/orders": {
    params: {};
  };
  "/routes": {
    params: {};
  };
  "/shipments/:id": {
    params: {
      "id": string;
    };
  };
  "/templates/:id": {
    params: {
      "id": string;
    };
  };
  "/app/webhooks": {
    params: {};
  };
  "/app/webhooks/receive": {
    params: {};
  };
  "/app/webhooks/:id": {
    params: {
      "id": string;
    };
  };
  "/audit": {
    params: {};
  };
  "/payments/:id": {
    params: {
      "id": string;
    };
  };
  "/users": {
    params: {};
  };
  "/zones": {
    params: {};
  };
  "/auth": {
    params: {};
  };
  "/drivers/:id": {
    params: {
      "id": string;
    };
  };
  "/support/:id": {
    params: {
      "id": string;
    };
  };
  "/onboarding": {
    params: {};
  };
  "/orders/:id": {
    params: {
      "id": string;
    };
  };
  "/pos": {
    params: {};
  };
  "/routes/:id": {
    params: {
      "id": string;
    };
  };
  "/api/proxy": {
    params: {};
  };
  "/uninstall": {
    params: {};
  };
  "/zones/:id": {
    params: {
      "id": string;
    };
  };
  "/install": {
    params: {};
  };
  "/pos/:id": {
    params: {
      "id": string;
    };
  };
  "/health": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/shipping-profiles" | "/api/webhooks/workflow" | "/auth-providers" | "/notifications" | "/integrations" | "/auth/session-token" | "/collections" | "/time-slots" | "/analytics" | "/auth/exit-iframe" | "/billing/invoices" | "/campaigns" | "/customers" | "/inventory" | "/locations" | "/shipments" | "/templates" | "/activity" | "/calendar" | "/payments" | "/settings" | "/billing" | "/drivers" | "/support" | "/auth/callback" | "/campaigns/:id" | "/customers/:id" | "/inventory/:id" | "/orders" | "/routes" | "/shipments/:id" | "/templates/:id" | "/app/webhooks" | "/app/webhooks/receive" | "/app/webhooks/:id" | "/audit" | "/payments/:id" | "/users" | "/zones" | "/auth" | "/drivers/:id" | "/support/:id" | "/onboarding" | "/orders/:id" | "/pos" | "/routes/:id" | "/api/proxy" | "/uninstall" | "/zones/:id" | "/install" | "/pos/:id" | "/health";
  };
  "routes/shipping-profiles._index.tsx": {
    id: "routes/shipping-profiles._index";
    page: "/shipping-profiles";
  };
  "routes/api.webhooks.workflow.tsx": {
    id: "routes/api.webhooks.workflow";
    page: "/api/webhooks/workflow";
  };
  "routes/auth-providers._index.tsx": {
    id: "routes/auth-providers._index";
    page: "/auth-providers";
  };
  "routes/notifications._index.tsx": {
    id: "routes/notifications._index";
    page: "/notifications";
  };
  "routes/integrations._index.tsx": {
    id: "routes/integrations._index";
    page: "/integrations";
  };
  "routes/auth.session-token.tsx": {
    id: "routes/auth.session-token";
    page: "/auth/session-token";
  };
  "routes/collections._index.tsx": {
    id: "routes/collections._index";
    page: "/collections";
  };
  "routes/time-slots._index.tsx": {
    id: "routes/time-slots._index";
    page: "/time-slots";
  };
  "routes/analytics._index.tsx": {
    id: "routes/analytics._index";
    page: "/analytics";
  };
  "routes/auth.exit-iframe.tsx": {
    id: "routes/auth.exit-iframe";
    page: "/auth/exit-iframe";
  };
  "routes/billing.invoices.tsx": {
    id: "routes/billing.invoices";
    page: "/billing/invoices";
  };
  "routes/campaigns._index.tsx": {
    id: "routes/campaigns._index";
    page: "/campaigns";
  };
  "routes/customers._index.tsx": {
    id: "routes/customers._index";
    page: "/customers";
  };
  "routes/inventory._index.tsx": {
    id: "routes/inventory._index";
    page: "/inventory";
  };
  "routes/locations._index.tsx": {
    id: "routes/locations._index";
    page: "/locations";
  };
  "routes/shipments._index.tsx": {
    id: "routes/shipments._index";
    page: "/shipments";
  };
  "routes/templates._index.tsx": {
    id: "routes/templates._index";
    page: "/templates";
  };
  "routes/activity._index.tsx": {
    id: "routes/activity._index";
    page: "/activity";
  };
  "routes/calendar._index.tsx": {
    id: "routes/calendar._index";
    page: "/calendar";
  };
  "routes/payments._index.tsx": {
    id: "routes/payments._index";
    page: "/payments";
  };
  "routes/settings._index.tsx": {
    id: "routes/settings._index";
    page: "/settings";
  };
  "routes/billing._index.tsx": {
    id: "routes/billing._index";
    page: "/billing";
  };
  "routes/drivers._index.tsx": {
    id: "routes/drivers._index";
    page: "/drivers";
  };
  "routes/support._index.tsx": {
    id: "routes/support._index";
    page: "/support";
  };
  "routes/auth.callback.tsx": {
    id: "routes/auth.callback";
    page: "/auth/callback";
  };
  "routes/campaigns.$id.tsx": {
    id: "routes/campaigns.$id";
    page: "/campaigns/:id";
  };
  "routes/customers.$id.tsx": {
    id: "routes/customers.$id";
    page: "/customers/:id";
  };
  "routes/inventory.$id.tsx": {
    id: "routes/inventory.$id";
    page: "/inventory/:id";
  };
  "routes/orders._index.tsx": {
    id: "routes/orders._index";
    page: "/orders";
  };
  "routes/routes._index.tsx": {
    id: "routes/routes._index";
    page: "/routes";
  };
  "routes/shipments.$id.tsx": {
    id: "routes/shipments.$id";
    page: "/shipments/:id";
  };
  "routes/templates.$id.tsx": {
    id: "routes/templates.$id";
    page: "/templates/:id";
  };
  "routes/app.webhooks.tsx": {
    id: "routes/app.webhooks";
    page: "/app/webhooks" | "/app/webhooks/receive" | "/app/webhooks/:id";
  };
  "routes/app.webhooks.receive.tsx": {
    id: "routes/app.webhooks.receive";
    page: "/app/webhooks/receive";
  };
  "routes/app.webhooks.$id.tsx": {
    id: "routes/app.webhooks.$id";
    page: "/app/webhooks/:id";
  };
  "routes/audit._index.tsx": {
    id: "routes/audit._index";
    page: "/audit";
  };
  "routes/payments.$id.tsx": {
    id: "routes/payments.$id";
    page: "/payments/:id";
  };
  "routes/users._index.tsx": {
    id: "routes/users._index";
    page: "/users";
  };
  "routes/zones._index.tsx": {
    id: "routes/zones._index";
    page: "/zones";
  };
  "routes/auth._index.tsx": {
    id: "routes/auth._index";
    page: "/auth";
  };
  "routes/drivers.$id.tsx": {
    id: "routes/drivers.$id";
    page: "/drivers/:id";
  };
  "routes/support.$id.tsx": {
    id: "routes/support.$id";
    page: "/support/:id";
  };
  "routes/onboarding.tsx": {
    id: "routes/onboarding";
    page: "/onboarding";
  };
  "routes/orders.$id.tsx": {
    id: "routes/orders.$id";
    page: "/orders/:id";
  };
  "routes/pos._index.tsx": {
    id: "routes/pos._index";
    page: "/pos";
  };
  "routes/routes.$id.tsx": {
    id: "routes/routes.$id";
    page: "/routes/:id";
  };
  "routes/api.proxy.tsx": {
    id: "routes/api.proxy";
    page: "/api/proxy";
  };
  "routes/uninstall.tsx": {
    id: "routes/uninstall";
    page: "/uninstall";
  };
  "routes/zones.$id.tsx": {
    id: "routes/zones.$id";
    page: "/zones/:id";
  };
  "routes/install.tsx": {
    id: "routes/install";
    page: "/install";
  };
  "routes/pos.$id.tsx": {
    id: "routes/pos.$id";
    page: "/pos/:id";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/health.tsx": {
    id: "routes/health";
    page: "/health";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/shipping-profiles._index": typeof import("./app/routes/shipping-profiles._index.tsx");
  "routes/api.webhooks.workflow": typeof import("./app/routes/api.webhooks.workflow.tsx");
  "routes/auth-providers._index": typeof import("./app/routes/auth-providers._index.tsx");
  "routes/notifications._index": typeof import("./app/routes/notifications._index.tsx");
  "routes/integrations._index": typeof import("./app/routes/integrations._index.tsx");
  "routes/auth.session-token": typeof import("./app/routes/auth.session-token.tsx");
  "routes/collections._index": typeof import("./app/routes/collections._index.tsx");
  "routes/time-slots._index": typeof import("./app/routes/time-slots._index.tsx");
  "routes/analytics._index": typeof import("./app/routes/analytics._index.tsx");
  "routes/auth.exit-iframe": typeof import("./app/routes/auth.exit-iframe.tsx");
  "routes/billing.invoices": typeof import("./app/routes/billing.invoices.tsx");
  "routes/campaigns._index": typeof import("./app/routes/campaigns._index.tsx");
  "routes/customers._index": typeof import("./app/routes/customers._index.tsx");
  "routes/inventory._index": typeof import("./app/routes/inventory._index.tsx");
  "routes/locations._index": typeof import("./app/routes/locations._index.tsx");
  "routes/shipments._index": typeof import("./app/routes/shipments._index.tsx");
  "routes/templates._index": typeof import("./app/routes/templates._index.tsx");
  "routes/activity._index": typeof import("./app/routes/activity._index.tsx");
  "routes/calendar._index": typeof import("./app/routes/calendar._index.tsx");
  "routes/payments._index": typeof import("./app/routes/payments._index.tsx");
  "routes/settings._index": typeof import("./app/routes/settings._index.tsx");
  "routes/billing._index": typeof import("./app/routes/billing._index.tsx");
  "routes/drivers._index": typeof import("./app/routes/drivers._index.tsx");
  "routes/support._index": typeof import("./app/routes/support._index.tsx");
  "routes/auth.callback": typeof import("./app/routes/auth.callback.tsx");
  "routes/campaigns.$id": typeof import("./app/routes/campaigns.$id.tsx");
  "routes/customers.$id": typeof import("./app/routes/customers.$id.tsx");
  "routes/inventory.$id": typeof import("./app/routes/inventory.$id.tsx");
  "routes/orders._index": typeof import("./app/routes/orders._index.tsx");
  "routes/routes._index": typeof import("./app/routes/routes._index.tsx");
  "routes/shipments.$id": typeof import("./app/routes/shipments.$id.tsx");
  "routes/templates.$id": typeof import("./app/routes/templates.$id.tsx");
  "routes/app.webhooks": typeof import("./app/routes/app.webhooks.tsx");
  "routes/app.webhooks.receive": typeof import("./app/routes/app.webhooks.receive.tsx");
  "routes/app.webhooks.$id": typeof import("./app/routes/app.webhooks.$id.tsx");
  "routes/audit._index": typeof import("./app/routes/audit._index.tsx");
  "routes/payments.$id": typeof import("./app/routes/payments.$id.tsx");
  "routes/users._index": typeof import("./app/routes/users._index.tsx");
  "routes/zones._index": typeof import("./app/routes/zones._index.tsx");
  "routes/auth._index": typeof import("./app/routes/auth._index.tsx");
  "routes/drivers.$id": typeof import("./app/routes/drivers.$id.tsx");
  "routes/support.$id": typeof import("./app/routes/support.$id.tsx");
  "routes/onboarding": typeof import("./app/routes/onboarding.tsx");
  "routes/orders.$id": typeof import("./app/routes/orders.$id.tsx");
  "routes/pos._index": typeof import("./app/routes/pos._index.tsx");
  "routes/routes.$id": typeof import("./app/routes/routes.$id.tsx");
  "routes/api.proxy": typeof import("./app/routes/api.proxy.tsx");
  "routes/uninstall": typeof import("./app/routes/uninstall.tsx");
  "routes/zones.$id": typeof import("./app/routes/zones.$id.tsx");
  "routes/install": typeof import("./app/routes/install.tsx");
  "routes/pos.$id": typeof import("./app/routes/pos.$id.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/health": typeof import("./app/routes/health.tsx");
};