import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './content/**/*.{md,mdx}',
    './node_modules/fumadocs-ui/dist/**/*.js',
  ],
  theme: {
    extend: {
      colors: {
        forge: {
          bg: '#0a0a0a',
          surface: '#141414',
          elevated: '#1c1c1c',
          raised: '#252525',
          border: '#2a2a2a',
          'border-light': '#3a3a3a',
        },
        teal: {
          DEFAULT: '#2A9D8F',
          light: '#3DB8A9',
          lighter: '#5ECEC0',
          dark: '#228176',
          darker: '#1A665C',
          glow: 'rgba(42, 157, 143, 0.15)',
        },
        coral: {
          DEFAULT: '#E76F51',
          light: '#EE8B72',
          lighter: '#F4A794',
          dark: '#D35A3D',
          darker: '#B84A31',
          glow: 'rgba(231, 111, 81, 0.15)',
        },
        sand: {
          DEFAULT: '#fafaf9',
          muted: '#a8a29e',
          dim: '#78716c',
          faint: '#57534e',
        },
      },
      fontFamily: {
        display: ['"Bricolage Grotesque"', 'system-ui', 'sans-serif'],
        sans: ['"DM Sans"', 'system-ui', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'ui-monospace', 'monospace'],
      },
      typography: {
        DEFAULT: {
          css: {
            '--tw-prose-body': '#d6d3d1',
            '--tw-prose-headings': '#fafaf9',
            '--tw-prose-links': '#2A9D8F',
            '--tw-prose-bold': '#fafaf9',
            '--tw-prose-counters': '#2A9D8F',
            '--tw-prose-bullets': '#2A9D8F',
            '--tw-prose-hr': '#2a2a2a',
            '--tw-prose-quotes': '#a8a29e',
            '--tw-prose-quote-borders': '#E76F51',
            '--tw-prose-code': '#3DB8A9',
            '--tw-prose-pre-bg': '#141414',
            '--tw-prose-pre-code': '#d6d3d1',
            '--tw-prose-th-borders': '#2a2a2a',
            '--tw-prose-td-borders': '#2a2a2a',
            color: '#d6d3d1',
            a: {
              color: '#2A9D8F',
              textDecoration: 'none',
              fontWeight: '500',
              '&:hover': { color: '#3DB8A9' },
            },
            code: {
              color: '#3DB8A9',
              backgroundColor: '#1c1c1c',
              padding: '0.2em 0.4em',
              borderRadius: '0.375rem',
              fontWeight: '400',
              fontSize: '0.875em',
            },
            'code::before': { content: '""' },
            'code::after': { content: '""' },
            pre: {
              backgroundColor: '#141414',
              color: '#d6d3d1',
              border: '1px solid #2a2a2a',
              borderRadius: '0.75rem',
            },
            'h1,h2,h3,h4,h5,h6': { color: '#fafaf9', fontFamily: '"Bricolage Grotesque", system-ui, sans-serif' },
            strong: { color: '#fafaf9' },
            blockquote: {
              color: '#a8a29e',
              borderLeftColor: '#E76F51',
              backgroundColor: 'rgba(231, 111, 81, 0.05)',
              borderRadius: '0 0.5rem 0.5rem 0',
              paddingRight: '1rem',
            },
            hr: { borderColor: '#2a2a2a' },
            th: { color: '#fafaf9', backgroundColor: '#1c1c1c', borderColor: '#2a2a2a' },
            td: { borderColor: '#2a2a2a' },
          },
        },
      },
      boxShadow: {
        'teal-sm': '0 1px 3px rgba(42, 157, 143, 0.08)',
        'teal-md': '0 4px 14px rgba(42, 157, 143, 0.12)',
        'teal-lg': '0 8px 30px rgba(42, 157, 143, 0.16)',
        'teal-glow': '0 0 40px rgba(42, 157, 143, 0.2)',
        'coral-glow': '0 0 40px rgba(231, 111, 81, 0.2)',
        'surface': '0 1px 3px rgba(0,0,0,0.3), 0 1px 2px rgba(0,0,0,0.4)',
        'elevated': '0 4px 6px rgba(0,0,0,0.3), 0 2px 4px rgba(0,0,0,0.4)',
        'raised': '0 10px 20px rgba(0,0,0,0.3), 0 6px 6px rgba(0,0,0,0.4)',
      },
      animation: {
        'fade-in': 'fadeIn 0.6s ease-out both',
        'fade-up': 'fadeUp 0.7s ease-out both',
        'glow-pulse': 'glowPulse 3s ease-in-out infinite',
        'terminal-blink': 'terminalBlink 1s step-end infinite',
        'scale-in': 'scaleIn 0.5s ease-out both',
        'spin': 'spin 1s linear infinite',
      },
      keyframes: {
        fadeIn: { '0%': { opacity: '0' }, '100%': { opacity: '1' } },
        fadeUp: { '0%': { opacity: '0', transform: 'translateY(24px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        glowPulse: { '0%, 100%': { opacity: '0.4' }, '50%': { opacity: '0.8' } },
        terminalBlink: { '0%, 100%': { opacity: '1' }, '50%': { opacity: '0' } },
        scaleIn: { '0%': { opacity: '0', transform: 'scale(0.95)' }, '100%': { opacity: '1', transform: 'scale(1)' } },
        spin: { '0%': { transform: 'rotate(0deg)' }, '100%': { transform: 'rotate(360deg)' } },
      },
    },
  },
  plugins: [require('@tailwindcss/typography')],
};

export default config;
