apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  labels:
    app.kubernetes.io/name: api
    app.kubernetes.io/part-of: witylogix
data:
  NODE_ENV: "production"
  PORT: "8000"
  HOST: "0.0.0.0"
  LOG_LEVEL: "info"
