import { stringify as stringifyYaml } from "yaml";
import type { BenchConfig, BenchConfigServices } from "@witylogix/bench-core";

/**
 * Generates a docker-compose.yml string from a BenchConfig.
 *
 * Deterministic: the same input always produces byte-identical output,
 * so it is safe to write unconditionally and diff against the previous
 * version to detect drift.
 */

type ServiceKey = keyof BenchConfigServices;
type ServiceDef = NonNullable<BenchConfigServices[ServiceKey]>;

interface ComposeOptions {
  imageRegistry?: string;
  imagePrefix?: string;
}

const DEFAULT_REGISTRY = "ghcr.io";
const DEFAULT_PREFIX = "wityliti/witylogix";

const DEFAULT_PORTS: Record<string, number> = {
  api: 8000,
  dashboard: 3003,
  "customer-portal": 3004,
  docs: 3005,
  "tracking-page": 3006,
};

const APP_SERVICES: readonly ServiceKey[] = [
  "api",
  "dashboard",
  "customer-portal",
  "tracking-page",
  "docs",
];

function witylogixImage(
  service: string,
  version: string,
  opts: ComposeOptions,
): string {
  const registry = opts.imageRegistry ?? DEFAULT_REGISTRY;
  const prefix = opts.imagePrefix ?? DEFAULT_PREFIX;
  return `${registry}/${prefix}-${service}:${version}`;
}

function appServiceBlock(
  name: string,
  svc: ServiceDef,
  config: BenchConfig,
  opts: ComposeOptions,
): Record<string, unknown> {
  const version = config.witylogix.version ?? "latest";
  const port = DEFAULT_PORTS[name];

  const block: Record<string, unknown> = {
    image: witylogixImage(name, version, opts),
    restart: "unless-stopped",
    depends_on: {
      postgres: { condition: "service_healthy" },
      redis: { condition: "service_healthy" },
    },
    environment: {
      NODE_ENV: "production",
      DATABASE_URL: "${DATABASE_URL}",
      REDIS_URL: "${REDIS_URL}",
      JWT_SECRET: "${JWT_SECRET}",
    },
    networks: ["bench"],
  };

  if (port) {
    block.ports = [`${port}:${port}`];
  }

  if (svc.domain) {
    const labels = block.labels as string[] | undefined;
    block.labels = [...(labels ?? []), `witylogix.domain=${svc.domain}`];
  }

  if (svc.replicas > 1) {
    block.deploy = { replicas: svc.replicas };
  }

  return block;
}

export function generateCompose(
  config: BenchConfig,
  opts: ComposeOptions = {},
): string {
  const services: Record<string, unknown> = {};

  services.postgres = {
    image: `postgis/postgis:${config.database.version}-3.4-alpine`,
    restart: "unless-stopped",
    environment: {
      POSTGRES_USER: "${POSTGRES_USER:-witylogix}",
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}",
      POSTGRES_DB: "${POSTGRES_DB:-witylogix}",
    },
    volumes: ["postgres_data:/var/lib/postgresql/data"],
    healthcheck: {
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-witylogix}"],
      interval: "10s",
      timeout: "5s",
      retries: 5,
      start_period: "10s",
    },
    networks: ["bench"],
  };

  services.redis = {
    image: `redis:${config.redis.version}-alpine`,
    restart: "unless-stopped",
    command: "redis-server --appendonly yes",
    volumes: ["redis_data:/data"],
    healthcheck: {
      test: ["CMD", "redis-cli", "ping"],
      interval: "10s",
      timeout: "5s",
      retries: 5,
      start_period: "10s",
    },
    networks: ["bench"],
  };

  for (const name of APP_SERVICES) {
    const svc = config.services[name];
    if (!svc) continue;
    services[name] = appServiceBlock(name, svc, config, opts);
  }

  const document = {
    name: config.metadata.name,
    services,
    networks: {
      bench: { driver: "bridge" },
    },
    volumes: {
      postgres_data: {},
      redis_data: {},
    },
  };

  return [
    `# Generated by @witylogix/bench — do not edit by hand.`,
    `# Source: bench.config.yaml (installation: ${config.metadata.name})`,
    "",
    stringifyYaml(document, { lineWidth: 120 }),
  ].join("\n");
}

export { APP_SERVICES, DEFAULT_PORTS };
