apiVersion: v1
kind: Service
metadata:
  name: shopify-app
  labels:
    app.kubernetes.io/name: shopify-app
    app.kubernetes.io/part-of: witylogix
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: shopify-app
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
