/**
 * Application configuration — validated at startup.
 * Fails fast if required environment variables are missing.
 */
import { z } from "zod";
declare const configSchema: z.ZodObject<{
    NODE_ENV: z.ZodDefault<z.ZodEnum<["development", "staging", "production"]>>;
    PORT: z.ZodDefault<z.ZodNumber>;
    HOST: z.ZodDefault<z.ZodString>;
    LOG_LEVEL: z.ZodDefault<z.ZodEnum<["fatal", "error", "warn", "info", "debug", "trace"]>>;
    DATABASE_URL: z.ZodString;
    REDIS_URL: z.ZodDefault<z.ZodString>;
    JWT_SECRET: z.ZodString;
    JWT_EXPIRES_IN: z.ZodDefault<z.ZodString>;
    SHOPIFY_API_KEY: z.ZodString;
    SHOPIFY_API_SECRET: z.ZodString;
    SHOPIFY_APP_URL: z.ZodOptional<z.ZodString>;
    SHOPIFY_SCOPES: z.ZodDefault<z.ZodString>;
    ROUTING_PROVIDER: z.ZodDefault<z.ZodEnum<["mapbox", "osrm", "google_maps", "here", "graphhopper", "tomtom"]>>;
    MAPBOX_ACCESS_TOKEN: z.ZodOptional<z.ZodString>;
    OSRM_BASE_URL: z.ZodOptional<z.ZodString>;
    GOOGLE_MAPS_API_KEY: z.ZodOptional<z.ZodString>;
    HERE_API_KEY: z.ZodOptional<z.ZodString>;
    GRAPHHOPPER_API_KEY: z.ZodOptional<z.ZodString>;
    TOMTOM_API_KEY: z.ZodOptional<z.ZodString>;
    ROUTING_BYOK: z.ZodEffects<z.ZodDefault<z.ZodEnum<["true", "false"]>>, boolean, "true" | "false" | undefined>;
    NOTIFICATIONS_BYOK: z.ZodEffects<z.ZodDefault<z.ZodEnum<["true", "false"]>>, boolean, "true" | "false" | undefined>;
    EMAIL_PROVIDER: z.ZodDefault<z.ZodEnum<["sendgrid", "mailgun", "aws_ses", "postmark", "resend", "smtp"]>>;
    SENDGRID_API_KEY: z.ZodOptional<z.ZodString>;
    MAILGUN_API_KEY: z.ZodOptional<z.ZodString>;
    MAILGUN_DOMAIN: z.ZodOptional<z.ZodString>;
    RESEND_API_KEY: z.ZodOptional<z.ZodString>;
    POSTMARK_SERVER_TOKEN: z.ZodOptional<z.ZodString>;
    AWS_SES_ACCESS_KEY_ID: z.ZodOptional<z.ZodString>;
    AWS_SES_SECRET_ACCESS_KEY: z.ZodOptional<z.ZodString>;
    AWS_SES_REGION: z.ZodOptional<z.ZodString>;
    SMTP_HOST: z.ZodOptional<z.ZodString>;
    SMTP_PORT: z.ZodOptional<z.ZodNumber>;
    SMTP_USERNAME: z.ZodOptional<z.ZodString>;
    SMTP_PASSWORD: z.ZodOptional<z.ZodString>;
    EMAIL_FROM: z.ZodOptional<z.ZodString>;
    EMAIL_FROM_NAME: z.ZodOptional<z.ZodString>;
    SMS_PROVIDER: z.ZodDefault<z.ZodEnum<["twilio", "vonage", "aws_sns", "messagebird", "plivo"]>>;
    TWILIO_ACCOUNT_SID: z.ZodOptional<z.ZodString>;
    TWILIO_AUTH_TOKEN: z.ZodOptional<z.ZodString>;
    TWILIO_PHONE_NUMBER: z.ZodOptional<z.ZodString>;
    VONAGE_API_KEY: z.ZodOptional<z.ZodString>;
    VONAGE_API_SECRET: z.ZodOptional<z.ZodString>;
    AWS_SNS_ACCESS_KEY_ID: z.ZodOptional<z.ZodString>;
    AWS_SNS_SECRET_ACCESS_KEY: z.ZodOptional<z.ZodString>;
    AWS_SNS_REGION: z.ZodOptional<z.ZodString>;
    MESSAGEBIRD_API_KEY: z.ZodOptional<z.ZodString>;
    PLIVO_AUTH_ID: z.ZodOptional<z.ZodString>;
    PLIVO_AUTH_TOKEN: z.ZodOptional<z.ZodString>;
    WHATSAPP_PROVIDER: z.ZodDefault<z.ZodEnum<["meta_cloud", "twilio_whatsapp", "360dialog"]>>;
    WHATSAPP_TOKEN: z.ZodOptional<z.ZodString>;
    WHATSAPP_PHONE_NUMBER_ID: z.ZodOptional<z.ZodString>;
    DIALOG360_API_KEY: z.ZodOptional<z.ZodString>;
    PUSH_PROVIDER: z.ZodDefault<z.ZodEnum<["firebase", "onesignal", "expo_push"]>>;
    FIREBASE_PROJECT_ID: z.ZodOptional<z.ZodString>;
    FIREBASE_PRIVATE_KEY: z.ZodOptional<z.ZodString>;
    FIREBASE_CLIENT_EMAIL: z.ZodOptional<z.ZodString>;
    ONESIGNAL_APP_ID: z.ZodOptional<z.ZodString>;
    ONESIGNAL_REST_API_KEY: z.ZodOptional<z.ZodString>;
    TRACKING_PAGE_URL: z.ZodDefault<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    NODE_ENV: "development" | "production" | "staging";
    PORT: number;
    HOST: string;
    LOG_LEVEL: "info" | "warn" | "error" | "fatal" | "debug" | "trace";
    DATABASE_URL: string;
    REDIS_URL: string;
    JWT_SECRET: string;
    JWT_EXPIRES_IN: string;
    SHOPIFY_API_KEY: string;
    SHOPIFY_API_SECRET: string;
    SHOPIFY_SCOPES: string;
    ROUTING_PROVIDER: "mapbox" | "osrm" | "google_maps" | "here" | "graphhopper" | "tomtom";
    ROUTING_BYOK: boolean;
    NOTIFICATIONS_BYOK: boolean;
    EMAIL_PROVIDER: "sendgrid" | "mailgun" | "aws_ses" | "postmark" | "resend" | "smtp";
    SMS_PROVIDER: "twilio" | "vonage" | "aws_sns" | "messagebird" | "plivo";
    WHATSAPP_PROVIDER: "meta_cloud" | "twilio_whatsapp" | "360dialog";
    PUSH_PROVIDER: "firebase" | "onesignal" | "expo_push";
    TRACKING_PAGE_URL: string;
    SHOPIFY_APP_URL?: string | undefined;
    MAPBOX_ACCESS_TOKEN?: string | undefined;
    OSRM_BASE_URL?: string | undefined;
    GOOGLE_MAPS_API_KEY?: string | undefined;
    HERE_API_KEY?: string | undefined;
    GRAPHHOPPER_API_KEY?: string | undefined;
    TOMTOM_API_KEY?: string | undefined;
    SENDGRID_API_KEY?: string | undefined;
    MAILGUN_API_KEY?: string | undefined;
    MAILGUN_DOMAIN?: string | undefined;
    RESEND_API_KEY?: string | undefined;
    POSTMARK_SERVER_TOKEN?: string | undefined;
    AWS_SES_ACCESS_KEY_ID?: string | undefined;
    AWS_SES_SECRET_ACCESS_KEY?: string | undefined;
    AWS_SES_REGION?: string | undefined;
    SMTP_HOST?: string | undefined;
    SMTP_PORT?: number | undefined;
    SMTP_USERNAME?: string | undefined;
    SMTP_PASSWORD?: string | undefined;
    EMAIL_FROM?: string | undefined;
    EMAIL_FROM_NAME?: string | undefined;
    TWILIO_ACCOUNT_SID?: string | undefined;
    TWILIO_AUTH_TOKEN?: string | undefined;
    TWILIO_PHONE_NUMBER?: string | undefined;
    VONAGE_API_KEY?: string | undefined;
    VONAGE_API_SECRET?: string | undefined;
    AWS_SNS_ACCESS_KEY_ID?: string | undefined;
    AWS_SNS_SECRET_ACCESS_KEY?: string | undefined;
    AWS_SNS_REGION?: string | undefined;
    MESSAGEBIRD_API_KEY?: string | undefined;
    PLIVO_AUTH_ID?: string | undefined;
    PLIVO_AUTH_TOKEN?: string | undefined;
    WHATSAPP_TOKEN?: string | undefined;
    WHATSAPP_PHONE_NUMBER_ID?: string | undefined;
    DIALOG360_API_KEY?: string | undefined;
    FIREBASE_PROJECT_ID?: string | undefined;
    FIREBASE_PRIVATE_KEY?: string | undefined;
    FIREBASE_CLIENT_EMAIL?: string | undefined;
    ONESIGNAL_APP_ID?: string | undefined;
    ONESIGNAL_REST_API_KEY?: string | undefined;
}, {
    DATABASE_URL: string;
    JWT_SECRET: string;
    SHOPIFY_API_KEY: string;
    SHOPIFY_API_SECRET: string;
    NODE_ENV?: "development" | "production" | "staging" | undefined;
    PORT?: number | undefined;
    HOST?: string | undefined;
    LOG_LEVEL?: "info" | "warn" | "error" | "fatal" | "debug" | "trace" | undefined;
    REDIS_URL?: string | undefined;
    JWT_EXPIRES_IN?: string | undefined;
    SHOPIFY_APP_URL?: string | undefined;
    SHOPIFY_SCOPES?: string | undefined;
    ROUTING_PROVIDER?: "mapbox" | "osrm" | "google_maps" | "here" | "graphhopper" | "tomtom" | undefined;
    MAPBOX_ACCESS_TOKEN?: string | undefined;
    OSRM_BASE_URL?: string | undefined;
    GOOGLE_MAPS_API_KEY?: string | undefined;
    HERE_API_KEY?: string | undefined;
    GRAPHHOPPER_API_KEY?: string | undefined;
    TOMTOM_API_KEY?: string | undefined;
    ROUTING_BYOK?: "true" | "false" | undefined;
    NOTIFICATIONS_BYOK?: "true" | "false" | undefined;
    EMAIL_PROVIDER?: "sendgrid" | "mailgun" | "aws_ses" | "postmark" | "resend" | "smtp" | undefined;
    SENDGRID_API_KEY?: string | undefined;
    MAILGUN_API_KEY?: string | undefined;
    MAILGUN_DOMAIN?: string | undefined;
    RESEND_API_KEY?: string | undefined;
    POSTMARK_SERVER_TOKEN?: string | undefined;
    AWS_SES_ACCESS_KEY_ID?: string | undefined;
    AWS_SES_SECRET_ACCESS_KEY?: string | undefined;
    AWS_SES_REGION?: string | undefined;
    SMTP_HOST?: string | undefined;
    SMTP_PORT?: number | undefined;
    SMTP_USERNAME?: string | undefined;
    SMTP_PASSWORD?: string | undefined;
    EMAIL_FROM?: string | undefined;
    EMAIL_FROM_NAME?: string | undefined;
    SMS_PROVIDER?: "twilio" | "vonage" | "aws_sns" | "messagebird" | "plivo" | undefined;
    TWILIO_ACCOUNT_SID?: string | undefined;
    TWILIO_AUTH_TOKEN?: string | undefined;
    TWILIO_PHONE_NUMBER?: string | undefined;
    VONAGE_API_KEY?: string | undefined;
    VONAGE_API_SECRET?: string | undefined;
    AWS_SNS_ACCESS_KEY_ID?: string | undefined;
    AWS_SNS_SECRET_ACCESS_KEY?: string | undefined;
    AWS_SNS_REGION?: string | undefined;
    MESSAGEBIRD_API_KEY?: string | undefined;
    PLIVO_AUTH_ID?: string | undefined;
    PLIVO_AUTH_TOKEN?: string | undefined;
    WHATSAPP_PROVIDER?: "meta_cloud" | "twilio_whatsapp" | "360dialog" | undefined;
    WHATSAPP_TOKEN?: string | undefined;
    WHATSAPP_PHONE_NUMBER_ID?: string | undefined;
    DIALOG360_API_KEY?: string | undefined;
    PUSH_PROVIDER?: "firebase" | "onesignal" | "expo_push" | undefined;
    FIREBASE_PROJECT_ID?: string | undefined;
    FIREBASE_PRIVATE_KEY?: string | undefined;
    FIREBASE_CLIENT_EMAIL?: string | undefined;
    ONESIGNAL_APP_ID?: string | undefined;
    ONESIGNAL_REST_API_KEY?: string | undefined;
    TRACKING_PAGE_URL?: string | undefined;
}>;
export type Config = z.infer<typeof configSchema>;
export declare function getConfig(): Config;
export declare function isDev(): boolean;
export declare function isProd(): boolean;
export {};
//# sourceMappingURL=config.d.ts.map