[build]
builder = "dockerfile"
dockerfilePath = "../../Dockerfile.shopify-app"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 60
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[service]
internalPort = 3000
