# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "797a3289c481d36f18c0d70fe1bbc261"
name = "witylogix"
application_url = "https://localhost:9293"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

[access_scopes]
scopes = "read_products,write_products,read_orders,write_orders,read_fulfillments,write_fulfillments,read_shipping,write_shipping,read_locations,read_inventory,write_inventory,read_customers"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://localhost:9293/auth/callback" ]

[pos]
embedded = false
