/**
 * Witylogix Integration Registry
 *
 * Comprehensive integration catalog covering 150+ providers across
 * routing, maps, telematics, messaging, email, collaboration,
 * supply chain, e-commerce, payments, ERP/accounting, CRM,
 * fuel/fleet, ELD, freight, analytics, e-signatures, shipping,
 * last-mile delivery, POS, healthcare, and field service categories.
 */

export type IntegrationCategory =
  | 'routing' | 'maps' | 'telematics' | 'messaging' | 'email'
  | 'collaboration' | 'supply-chain' | 'e-commerce' | 'payments'
  | 'erp-accounting' | 'crm' | 'fuel-fleet' | 'eld' | 'freight'
  | 'analytics' | 'e-signatures' | 'shipping' | 'last-mile'
  | 'pos-restaurant' | 'healthcare' | 'field-service';

export type AuthMethod = 'api-key' | 'oauth2' | 'basic' | 'bearer' | 'hmac' | 'jwt' | 'custom';

export type AdapterStatus = 'production' | 'beta' | 'alpha' | 'planned' | 'community';

export interface IntegrationProvider {
  readonly id: string;
  readonly name: string;
  readonly category: IntegrationCategory;
  readonly description: string;
  readonly authMethod: AuthMethod;
  readonly apiBaseUrl: string;
  readonly docsUrl: string;
  readonly operations: readonly string[];
  readonly status: AdapterStatus;
  readonly webhookSupport: boolean;
  readonly rateLimitRpm?: number;
}

export const ALL_PROVIDERS: readonly IntegrationProvider[] = [
  { id: 'valhalla', name: 'Valhalla', category: 'routing', description: 'Open-source routing engine — turn-by-turn, isochrones, matrix, map-matching', authMethod: 'api-key', apiBaseUrl: 'https://valhalla.openstreetmap.de', docsUrl: 'https://valhalla.github.io/valhalla/', operations: ['route', 'optimized-route', 'isochrone', 'matrix', 'map-match'], status: 'production', webhookSupport: false },
  { id: 'vroom', name: 'VROOM', category: 'routing', description: 'Open-source vehicle routing optimization — CVRP, VRPTW, pickup-delivery', authMethod: 'api-key', apiBaseUrl: 'https://solver.vroom-project.org', docsUrl: 'https://github.com/VROOM-Project/vroom', operations: ['optimize', 'vrp-solve', 'pickup-delivery', 'time-windows'], status: 'production', webhookSupport: false },
  { id: 'google-routes-api', name: 'Google Routes API', category: 'routing', description: 'Compute routes, route matrix, traffic-aware ETAs', authMethod: 'api-key', apiBaseUrl: 'https://routes.googleapis.com', docsUrl: 'https://developers.google.com/maps/documentation/routes', operations: ['compute-routes', 'route-matrix', 'traffic-eta'], status: 'production', webhookSupport: false },
  { id: 'mapbox-directions', name: 'Mapbox Directions', category: 'routing', description: 'Turn-by-turn navigation, optimization, isochrones', authMethod: 'bearer', apiBaseUrl: 'https://api.mapbox.com/directions/v5', docsUrl: 'https://docs.mapbox.com/api/navigation/directions/', operations: ['directions', 'optimization', 'isochrone', 'map-matching'], status: 'production', webhookSupport: false },
  { id: 'here-routing', name: 'HERE Routing', category: 'routing', description: 'Fleet routing, truck routing, EV routing, waypoint sequencing', authMethod: 'api-key', apiBaseUrl: 'https://router.hereapi.com/v8', docsUrl: 'https://developer.here.com/', operations: ['route', 'matrix', 'truck-route', 'ev-route'], status: 'production', webhookSupport: false },
  { id: 'route4me', name: 'Route4Me', category: 'routing', description: 'Multi-stop route planning, fleet management, territory planning', authMethod: 'api-key', apiBaseUrl: 'https://api.route4me.com', docsUrl: 'https://route4me.io/docs/', operations: ['optimize-route', 'tracking', 'territory', 'fleet'], status: 'production', webhookSupport: true },
  { id: 'optimoroute', name: 'OptimoRoute', category: 'routing', description: 'Route planning, real-time order scheduling, proof of delivery', authMethod: 'api-key', apiBaseUrl: 'https://api.optimoroute.com/v1', docsUrl: 'https://docs.optimoroute.com/', operations: ['plan-routes', 'get-routes', 'update-order'], status: 'production', webhookSupport: true },
  { id: 'routific', name: 'Routific', category: 'routing', description: 'Route optimization, live ETAs, customer notifications', authMethod: 'bearer', apiBaseUrl: 'https://api.routific.com/v1', docsUrl: 'https://docs.routific.com/', operations: ['vrp', 'pdp', 'live-eta', 'dispatch'], status: 'production', webhookSupport: true },
  { id: 'google-maps', name: 'Google Maps', category: 'maps', description: 'Geocoding, places, distance matrix, static/dynamic maps', authMethod: 'api-key', apiBaseUrl: 'https://maps.googleapis.com/maps/api', docsUrl: 'https://developers.google.com/maps', operations: ['geocode', 'places', 'distance-matrix', 'directions'], status: 'production', webhookSupport: false },
  { id: 'mapbox', name: 'Mapbox', category: 'maps', description: 'Vector tiles, geocoding, static images, navigation SDK', authMethod: 'bearer', apiBaseUrl: 'https://api.mapbox.com', docsUrl: 'https://docs.mapbox.com/', operations: ['geocode', 'tiles', 'static-images', 'navigation'], status: 'production', webhookSupport: false },
  { id: 'openstreetmap', name: 'OpenStreetMap', category: 'maps', description: 'Free geocoding, reverse geocoding, address lookup via Nominatim', authMethod: 'api-key', apiBaseUrl: 'https://nominatim.openstreetmap.org', docsUrl: 'https://nominatim.org/', operations: ['search', 'reverse', 'lookup'], status: 'production', webhookSupport: false },
  { id: 'here-maps', name: 'HERE Maps', category: 'maps', description: 'Geocoding, map tiles, fleet telematics, transit routing', authMethod: 'api-key', apiBaseUrl: 'https://geocode.search.hereapi.com/v1', docsUrl: 'https://developer.here.com/', operations: ['geocode', 'autosuggest', 'map-tiles', 'transit'], status: 'production', webhookSupport: false },
  { id: 'tomtom', name: 'TomTom', category: 'maps', description: 'Maps, search, routing, traffic flow, speed cameras', authMethod: 'api-key', apiBaseUrl: 'https://api.tomtom.com', docsUrl: 'https://developer.tomtom.com/', operations: ['search', 'route', 'traffic-flow', 'traffic-incidents'], status: 'production', webhookSupport: false },
  { id: 'flespi', name: 'Flespi', category: 'telematics', description: 'Universal telematics platform, 2500+ tracker protocols, MQTT/REST', authMethod: 'bearer', apiBaseUrl: 'https://flespi.io', docsUrl: 'https://flespi.com/kb', operations: ['devices', 'channels', 'streams', 'analytics', 'geofences'], status: 'production', webhookSupport: true },
  { id: 'geotab', name: 'Geotab', category: 'telematics', description: 'Vehicle tracking, engine diagnostics, driver behavior, fuel usage', authMethod: 'basic', apiBaseUrl: 'https://my.geotab.com/apiv1', docsUrl: 'https://geotab.github.io/sdk/', operations: ['device', 'status-data', 'log-record', 'trip', 'fault-data'], status: 'production', webhookSupport: true },
  { id: 'samsara', name: 'Samsara', category: 'telematics', description: 'Fleet GPS, DVIR, HOS, fuel, temperature, driver safety', authMethod: 'bearer', apiBaseUrl: 'https://api.samsara.com/v1', docsUrl: 'https://developers.samsara.com/', operations: ['fleet-locations', 'vehicle-stats', 'driver-safety', 'fuel', 'dvir'], status: 'production', webhookSupport: true },
  { id: 'verizon-connect', name: 'Verizon Connect', category: 'telematics', description: 'Fleet tracking, driver behavior, maintenance alerts', authMethod: 'oauth2', apiBaseUrl: 'https://fim.api.verizonconnect.com', docsUrl: 'https://developer.verizonconnect.com/', operations: ['vehicles', 'drivers', 'trips', 'alerts', 'maintenance'], status: 'production', webhookSupport: true },
  { id: 'trimble', name: 'Trimble', category: 'telematics', description: 'Fleet management, routing, visibility, fuel tax', authMethod: 'oauth2', apiBaseUrl: 'https://api.transportation.trimble.com', docsUrl: 'https://developer.trimble.com/', operations: ['vehicles', 'positions', 'trips', 'fuel', 'dispatch'], status: 'production', webhookSupport: true },
  { id: 'powerfleet', name: 'Powerfleet', category: 'telematics', description: 'Industrial fleet IoT, yard management, asset tracking', authMethod: 'api-key', apiBaseUrl: 'https://api.powerfleet.com', docsUrl: 'https://www.powerfleet.com/', operations: ['assets', 'vehicles', 'yard-management', 'utilization'], status: 'planned', webhookSupport: true },
  { id: 'azuga', name: 'Azuga', category: 'telematics', description: 'GPS fleet tracking, driver rewards, maintenance, fuel cards', authMethod: 'api-key', apiBaseUrl: 'https://api.azuga.com/v2', docsUrl: 'https://www.azuga.com/', operations: ['vehicles', 'trips', 'drivers', 'alerts', 'fuel'], status: 'planned', webhookSupport: true },
  { id: 'omnitracs', name: 'Omnitracs', category: 'telematics', description: 'Fleet intelligence, critical event video, driver workflow', authMethod: 'oauth2', apiBaseUrl: 'https://api.omnitracs.com', docsUrl: 'https://www.omnitracs.com/', operations: ['vehicles', 'drivers', 'eld', 'dispatch', 'video-safety'], status: 'planned', webhookSupport: true },
  { id: 'platform-science', name: 'Platform Science', category: 'telematics', description: 'Open fleet platform, app marketplace for trucks, ELD', authMethod: 'oauth2', apiBaseUrl: 'https://api.platformscience.com', docsUrl: 'https://developer.platformscience.com/', operations: ['vehicles', 'apps', 'eld-data', 'workflows'], status: 'planned', webhookSupport: true },
  { id: 'fleetio', name: 'Fleetio', category: 'telematics', description: 'Fleet maintenance, fuel tracking, inspections, parts inventory', authMethod: 'bearer', apiBaseUrl: 'https://secure.fleetio.com/api/v2', docsUrl: 'https://developer.fleetio.com/', operations: ['vehicles', 'service-entries', 'fuel-entries', 'inspections'], status: 'production', webhookSupport: true },
  { id: 'clearpathgps', name: 'ClearPathGPS', category: 'telematics', description: 'Small fleet GPS tracking, geofences, engine diagnostics', authMethod: 'api-key', apiBaseUrl: 'https://api.clearpathgps.com', docsUrl: 'https://www.clearpathgps.com/', operations: ['devices', 'positions', 'geofences', 'alerts'], status: 'planned', webhookSupport: false },
  { id: 'one-step-gps', name: 'One Step GPS', category: 'telematics', description: 'Affordable fleet tracking, geofences, driver scorecards', authMethod: 'api-key', apiBaseUrl: 'https://track.onestepgps.com/v3/api', docsUrl: 'https://track.onestepgps.com/', operations: ['devices', 'positions', 'geofences', 'alerts'], status: 'planned', webhookSupport: false },
  { id: 'titan-gps', name: 'Titan GPS', category: 'telematics', description: 'Fleet tracking, asset trackers, dashcam integration', authMethod: 'api-key', apiBaseUrl: 'https://api.titangps.com', docsUrl: 'https://www.titangps.com/', operations: ['vehicles', 'positions', 'geofences', 'alerts'], status: 'planned', webhookSupport: false },
  { id: 'twilio', name: 'Twilio', category: 'messaging', description: 'SMS, MMS, WhatsApp, voice, verify, programmable messaging', authMethod: 'basic', apiBaseUrl: 'https://api.twilio.com/2010-04-01', docsUrl: 'https://www.twilio.com/docs', operations: ['send-sms', 'send-mms', 'send-whatsapp', 'verify'], status: 'production', webhookSupport: true },
  { id: 'whatsapp-business', name: 'WhatsApp Business', category: 'messaging', description: 'Meta Cloud API — template messages, interactive, media, catalog', authMethod: 'bearer', apiBaseUrl: 'https://graph.facebook.com/v18.0', docsUrl: 'https://developers.facebook.com/docs/whatsapp/', operations: ['send-template', 'send-text', 'send-media', 'manage-templates'], status: 'production', webhookSupport: true },
  { id: 'vonage', name: 'Vonage', category: 'messaging', description: 'SMS, MMS, WhatsApp, Viber, Facebook Messenger APIs', authMethod: 'api-key', apiBaseUrl: 'https://api.nexmo.com', docsUrl: 'https://developer.vonage.com/', operations: ['send-sms', 'send-mms', 'send-whatsapp', 'verify'], status: 'production', webhookSupport: true },
  { id: 'textmagic', name: 'TextMagic', category: 'messaging', description: 'Bulk SMS, two-way messaging, SMS gateway, email-to-SMS', authMethod: 'api-key', apiBaseUrl: 'https://rest.textmagic.com/api/v2', docsUrl: 'https://www.textmagic.com/docs/api/', operations: ['send-message', 'bulk-send', 'contacts', 'templates'], status: 'production', webhookSupport: true },
  { id: 'onesignal', name: 'OneSignal', category: 'messaging', description: 'Push notifications (web, mobile, in-app), email, SMS', authMethod: 'api-key', apiBaseUrl: 'https://onesignal.com/api/v1', docsUrl: 'https://documentation.onesignal.com/', operations: ['create-notification', 'segments', 'devices', 'templates'], status: 'production', webhookSupport: true },
  { id: 'sendbird', name: 'Sendbird', category: 'messaging', description: 'In-app chat, push notifications, chatbot integration', authMethod: 'api-key', apiBaseUrl: 'https://api.sendbird.com/v3', docsUrl: 'https://sendbird.com/docs', operations: ['send-message', 'create-channel', 'users', 'push'], status: 'production', webhookSupport: true },
  { id: 'firebase-cloud-messaging', name: 'Firebase Cloud Messaging', category: 'messaging', description: 'Cross-platform push notifications (Android, iOS, web)', authMethod: 'oauth2', apiBaseUrl: 'https://fcm.googleapis.com/v1', docsUrl: 'https://firebase.google.com/docs/cloud-messaging', operations: ['send', 'topic-send', 'condition-send'], status: 'production', webhookSupport: false },
  { id: 'sendgrid', name: 'SendGrid', category: 'email', description: 'Transactional email, marketing campaigns, templates, analytics', authMethod: 'bearer', apiBaseUrl: 'https://api.sendgrid.com/v3', docsUrl: 'https://docs.sendgrid.com/', operations: ['send-mail', 'templates', 'contacts', 'campaigns', 'statistics'], status: 'production', webhookSupport: true },
  { id: 'mailgun', name: 'Mailgun', category: 'email', description: 'Email API, validation, routing, templates, analytics', authMethod: 'basic', apiBaseUrl: 'https://api.mailgun.net/v3', docsUrl: 'https://documentation.mailgun.com/', operations: ['send-message', 'validate', 'routes', 'templates', 'events'], status: 'production', webhookSupport: true },
  { id: 'amazon-ses', name: 'Amazon SES', category: 'email', description: 'Scalable transactional + marketing email', authMethod: 'api-key', apiBaseUrl: 'https://email.amazonaws.com', docsUrl: 'https://docs.aws.amazon.com/ses/', operations: ['send-email', 'templates', 'identities', 'configuration-sets'], status: 'production', webhookSupport: true },
  { id: 'outlook', name: 'Outlook', category: 'email', description: 'Microsoft Graph Mail API — email, calendar, contacts', authMethod: 'oauth2', apiBaseUrl: 'https://graph.microsoft.com/v1.0', docsUrl: 'https://learn.microsoft.com/en-us/graph/', operations: ['send-mail', 'list-messages', 'create-draft', 'attachments'], status: 'production', webhookSupport: true },
  { id: 'gmail', name: 'Gmail', category: 'email', description: 'Gmail API — send, read, label, thread management', authMethod: 'oauth2', apiBaseUrl: 'https://gmail.googleapis.com/gmail/v1', docsUrl: 'https://developers.google.com/gmail/api', operations: ['send', 'list', 'get', 'modify', 'labels', 'drafts'], status: 'production', webhookSupport: true },
  { id: 'pusher', name: 'Pusher', category: 'collaboration', description: 'Real-time WebSocket infrastructure, presence channels', authMethod: 'api-key', apiBaseUrl: 'https://api.pusher.com', docsUrl: 'https://pusher.com/docs/channels/', operations: ['trigger-event', 'batch-trigger', 'channel-info'], status: 'planned', webhookSupport: true },
  { id: 'slack', name: 'Slack', category: 'collaboration', description: 'Messaging, channels, workflows, bots, file sharing', authMethod: 'oauth2', apiBaseUrl: 'https://slack.com/api', docsUrl: 'https://api.slack.com/', operations: ['post-message', 'conversations', 'files', 'workflows'], status: 'planned', webhookSupport: true },
  { id: 'microsoft-teams', name: 'Microsoft Teams', category: 'collaboration', description: 'Team messaging, channels, meetings, bots via Graph API', authMethod: 'oauth2', apiBaseUrl: 'https://graph.microsoft.com/v1.0', docsUrl: 'https://learn.microsoft.com/en-us/graph/', operations: ['send-message', 'create-channel', 'list-teams', 'meetings'], status: 'planned', webhookSupport: true },
  { id: 'track-pod', name: 'Track-POD', category: 'collaboration', description: 'Delivery management, proof of delivery, route optimization', authMethod: 'api-key', apiBaseUrl: 'https://api.track-pod.com/api', docsUrl: 'https://track-pod.com/', operations: ['orders', 'routes', 'drivers', 'pod', 'analytics'], status: 'planned', webhookSupport: true },
  { id: 'dispatchtrack', name: 'DispatchTrack', category: 'collaboration', description: 'Last-mile delivery management, route optimization', authMethod: 'api-key', apiBaseUrl: 'https://api.dispatchtrack.com', docsUrl: 'https://www.dispatchtrack.com/', operations: ['orders', 'routes', 'drivers', 'tracking'], status: 'planned', webhookSupport: true },
  { id: 'podium', name: 'Podium', category: 'collaboration', description: 'Customer messaging, reviews, payments, webchat', authMethod: 'oauth2', apiBaseUrl: 'https://api.podium.com/v4', docsUrl: 'https://docs.podium.com/', operations: ['send-message', 'contacts', 'reviews', 'payments'], status: 'planned', webhookSupport: true },
  { id: 'workwave', name: 'WorkWave', category: 'collaboration', description: 'Field service routing, GPS tracking, route optimization', authMethod: 'api-key', apiBaseUrl: 'https://api.workwave.com', docsUrl: 'https://www.workwave.com/', operations: ['orders', 'routes', 'vehicles', 'drivers'], status: 'planned', webhookSupport: true },
  { id: 'manhattan-associates', name: 'Manhattan Associates', category: 'supply-chain', description: 'Warehouse management, transportation management, yard management', authMethod: 'oauth2', apiBaseUrl: 'https://api.manh.com', docsUrl: 'https://www.manh.com/', operations: ['orders', 'inventory', 'shipments', 'warehouse'], status: 'planned', webhookSupport: true },
  { id: 'blue-yonder', name: 'Blue Yonder', category: 'supply-chain', description: 'Supply chain planning, WMS, TMS, demand forecasting', authMethod: 'oauth2', apiBaseUrl: 'https://api.blueyonder.com', docsUrl: 'https://blueyonder.com/', operations: ['demand-planning', 'fulfillment', 'warehouse', 'inventory'], status: 'planned', webhookSupport: true },
  { id: 'korber-supply-chain', name: 'Körber Supply Chain', category: 'supply-chain', description: 'Warehouse management, voice-directed, robotics', authMethod: 'oauth2', apiBaseUrl: 'https://api.koerber-supplychain.com', docsUrl: 'https://www.koerber-supplychain.com/', operations: ['warehouse', 'inventory', 'orders', 'robotics'], status: 'planned', webhookSupport: true },
  { id: 'deposco', name: 'Deposco', category: 'supply-chain', description: 'Fulfillment, warehouse management, order management', authMethod: 'api-key', apiBaseUrl: 'https://api.deposco.com', docsUrl: 'https://www.deposco.com/', operations: ['orders', 'inventory', 'fulfillment', 'warehouse'], status: 'planned', webhookSupport: true },
  { id: 'extensiv', name: 'Extensiv', category: 'supply-chain', description: '3PL WMS, order management, omnichannel fulfillment', authMethod: 'oauth2', apiBaseUrl: 'https://api.extensiv.com', docsUrl: 'https://www.extensiv.com/', operations: ['orders', 'inventory', 'warehouses', 'shipping'], status: 'planned', webhookSupport: true },
  { id: 'fishbowl', name: 'Fishbowl', category: 'supply-chain', description: 'Manufacturing & warehouse inventory, QuickBooks integration', authMethod: 'api-key', apiBaseUrl: 'https://api.fishbowlinventory.com', docsUrl: 'https://www.fishbowlinventory.com/', operations: ['inventory', 'orders', 'parts', 'manufacturing'], status: 'planned', webhookSupport: false },
  { id: 'shopify', name: 'Shopify', category: 'e-commerce', description: 'Orders, products, customers, inventory, fulfillment, checkout extensions', authMethod: 'oauth2', apiBaseUrl: 'https://{store}.myshopify.com/admin/api/2024-01', docsUrl: 'https://shopify.dev/docs/api', operations: ['orders', 'products', 'customers', 'inventory', 'fulfillment', 'webhooks'], status: 'production', webhookSupport: true },
  { id: 'woocommerce', name: 'WooCommerce', category: 'e-commerce', description: 'Orders, products, customers, coupons, shipping, webhooks', authMethod: 'basic', apiBaseUrl: 'https://{store}/wp-json/wc/v3', docsUrl: 'https://woocommerce.github.io/woocommerce-rest-api-docs/', operations: ['orders', 'products', 'customers', 'coupons', 'shipping', 'webhooks'], status: 'production', webhookSupport: true },
  { id: 'magento', name: 'Magento', category: 'e-commerce', description: 'Adobe Commerce — catalog, orders, customers, inventory, CMS', authMethod: 'oauth2', apiBaseUrl: 'https://{store}/rest/V1', docsUrl: 'https://developer.adobe.com/commerce/webapi/', operations: ['orders', 'products', 'customers', 'inventory', 'cart'], status: 'production', webhookSupport: true },
  { id: 'bigcommerce', name: 'BigCommerce', category: 'e-commerce', description: 'Catalog, orders, customers, pricing, shipping, webhooks', authMethod: 'oauth2', apiBaseUrl: 'https://api.bigcommerce.com/stores/{hash}/v3', docsUrl: 'https://developer.bigcommerce.com/', operations: ['orders', 'products', 'customers', 'carts', 'shipping'], status: 'production', webhookSupport: true },
  { id: 'amazon-seller-central', name: 'Amazon Seller Central', category: 'e-commerce', description: 'SP-API — orders, inventory, fulfillment (FBA/FBM), reports', authMethod: 'oauth2', apiBaseUrl: 'https://sellingpartnerapi-na.amazon.com', docsUrl: 'https://developer-docs.amazon.com/sp-api/', operations: ['orders', 'inventory', 'fulfillment', 'reports', 'catalog'], status: 'planned', webhookSupport: true },
  { id: 'ebay', name: 'eBay', category: 'e-commerce', description: 'Buy, sell, commerce, fulfillment, analytics', authMethod: 'oauth2', apiBaseUrl: 'https://api.ebay.com', docsUrl: 'https://developer.ebay.com/', operations: ['orders', 'inventory', 'fulfillment', 'catalog', 'analytics'], status: 'planned', webhookSupport: true },
  { id: 'etsy', name: 'Etsy', category: 'e-commerce', description: 'Listings, receipts, shipping, reviews, shop management', authMethod: 'oauth2', apiBaseUrl: 'https://api.etsy.com/v3', docsUrl: 'https://developer.etsy.com/', operations: ['listings', 'receipts', 'shipping-profiles', 'reviews'], status: 'planned', webhookSupport: false },
  { id: 'square-online', name: 'Square Online', category: 'e-commerce', description: 'Orders, catalog, inventory, customers, loyalty, payments', authMethod: 'oauth2', apiBaseUrl: 'https://connect.squareup.com/v2', docsUrl: 'https://developer.squareup.com/', operations: ['orders', 'catalog', 'inventory', 'customers', 'payments'], status: 'planned', webhookSupport: true },
  { id: 'stripe', name: 'Stripe', category: 'payments', description: 'Payment intents, subscriptions, invoices, checkout sessions', authMethod: 'bearer', apiBaseUrl: 'https://api.stripe.com/v1', docsUrl: 'https://docs.stripe.com/api', operations: ['payment-intents', 'subscriptions', 'invoices', 'checkout', 'refunds'], status: 'production', webhookSupport: true },
  { id: 'square-payments', name: 'Square', category: 'payments', description: 'In-person, online, invoices, terminal, gift cards', authMethod: 'oauth2', apiBaseUrl: 'https://connect.squareup.com/v2', docsUrl: 'https://developer.squareup.com/', operations: ['create-payment', 'refund', 'invoices', 'terminal'], status: 'production', webhookSupport: true },
  { id: 'paypal', name: 'PayPal', category: 'payments', description: 'Orders, payments, subscriptions, payouts, invoicing', authMethod: 'oauth2', apiBaseUrl: 'https://api-m.paypal.com/v2', docsUrl: 'https://developer.paypal.com/api/rest/', operations: ['create-order', 'capture-payment', 'subscriptions', 'payouts'], status: 'production', webhookSupport: true },
  { id: 'braintree', name: 'Braintree', category: 'payments', description: 'Credit cards, PayPal, Venmo, Apple Pay, Google Pay', authMethod: 'api-key', apiBaseUrl: 'https://api.braintreegateway.com', docsUrl: 'https://developer.paypal.com/braintree/docs', operations: ['transactions', 'customers', 'subscriptions', 'disputes'], status: 'planned', webhookSupport: true },
  { id: 'authorize-net', name: 'Authorize.Net', category: 'payments', description: 'Credit card processing, ACH, fraud detection, recurring billing', authMethod: 'api-key', apiBaseUrl: 'https://api.authorize.net/xml/v1', docsUrl: 'https://developer.authorize.net/', operations: ['charge', 'authorize', 'void', 'refund', 'subscriptions'], status: 'planned', webhookSupport: true },
  { id: 'adyen', name: 'Adyen', category: 'payments', description: 'Global payments, POS, online, in-app, marketplace payouts', authMethod: 'api-key', apiBaseUrl: 'https://checkout-test.adyen.com/v71', docsUrl: 'https://docs.adyen.com/', operations: ['payments', 'recurring', 'payouts', 'platforms', 'terminals'], status: 'planned', webhookSupport: true },
  { id: 'sap', name: 'SAP', category: 'erp-accounting', description: 'S/4HANA — ERP, supply chain, finance, procurement', authMethod: 'oauth2', apiBaseUrl: 'https://api.sap.com', docsUrl: 'https://api.sap.com/', operations: ['sales-orders', 'deliveries', 'materials', 'invoices'], status: 'production', webhookSupport: true },
  { id: 'oracle-netsuite', name: 'Oracle NetSuite', category: 'erp-accounting', description: 'ERP, CRM, e-commerce, financials, inventory', authMethod: 'oauth2', apiBaseUrl: 'https://{id}.suitetalk.api.netsuite.com', docsUrl: 'https://docs.oracle.com/en/cloud/saas/netsuite/', operations: ['sales-orders', 'invoices', 'inventory', 'customers'], status: 'production', webhookSupport: true },
  { id: 'microsoft-dynamics-365', name: 'Microsoft Dynamics 365', category: 'erp-accounting', description: 'Supply chain, finance, commerce, field service', authMethod: 'oauth2', apiBaseUrl: 'https://{org}.api.crm.dynamics.com', docsUrl: 'https://learn.microsoft.com/en-us/dynamics365/', operations: ['sales-orders', 'invoices', 'products', 'accounts'], status: 'production', webhookSupport: true },
  { id: 'sage', name: 'Sage', category: 'erp-accounting', description: 'Cloud accounting, invoicing, payroll, inventory', authMethod: 'oauth2', apiBaseUrl: 'https://api.accounting.sage.com/v3.1', docsUrl: 'https://developer.sage.com/', operations: ['invoices', 'contacts', 'ledger-accounts', 'bank-transactions'], status: 'production', webhookSupport: true },
  { id: 'infor', name: 'Infor', category: 'erp-accounting', description: 'Industry-specific ERP, WMS, supply chain, finance', authMethod: 'oauth2', apiBaseUrl: 'https://api.infor.com', docsUrl: 'https://www.infor.com/', operations: ['orders', 'inventory', 'manufacturing', 'finance'], status: 'planned', webhookSupport: true },
  { id: 'epicor', name: 'Epicor', category: 'erp-accounting', description: 'Manufacturing ERP, distribution, retail, automotive', authMethod: 'basic', apiBaseUrl: 'https://{server}/api/v2', docsUrl: 'https://www.epicor.com/', operations: ['sales-orders', 'parts', 'inventory', 'purchase-orders'], status: 'planned', webhookSupport: true },
  { id: 'quickbooks', name: 'QuickBooks', category: 'erp-accounting', description: 'Invoicing, expenses, payroll, reports, banking', authMethod: 'oauth2', apiBaseUrl: 'https://quickbooks.api.intuit.com/v3', docsUrl: 'https://developer.intuit.com/', operations: ['invoices', 'customers', 'payments', 'expenses', 'reports'], status: 'production', webhookSupport: true },
  { id: 'xero', name: 'Xero', category: 'erp-accounting', description: 'Accounting, invoicing, bank reconciliation, payroll', authMethod: 'oauth2', apiBaseUrl: 'https://api.xero.com/api.xro/2.0', docsUrl: 'https://developer.xero.com/', operations: ['invoices', 'contacts', 'payments', 'bank-transactions', 'reports'], status: 'production', webhookSupport: true },
  { id: 'sage-intacct', name: 'Sage Intacct', category: 'erp-accounting', description: 'Cloud financial management, multi-entity, project accounting', authMethod: 'custom', apiBaseUrl: 'https://api.intacct.com', docsUrl: 'https://developer.intacct.com/', operations: ['invoices', 'gl-entries', 'vendors', 'projects'], status: 'planned', webhookSupport: false },
  { id: 'freshbooks', name: 'FreshBooks', category: 'erp-accounting', description: 'Invoicing, expenses, time tracking, payments', authMethod: 'oauth2', apiBaseUrl: 'https://api.freshbooks.com', docsUrl: 'https://www.freshbooks.com/api/', operations: ['invoices', 'clients', 'expenses', 'payments', 'time-entries'], status: 'planned', webhookSupport: true },
  { id: 'wave', name: 'Wave', category: 'erp-accounting', description: 'Free invoicing, accounting, receipt scanning, payroll', authMethod: 'oauth2', apiBaseUrl: 'https://gql.waveapps.com/graphql/public', docsUrl: 'https://developer.waveapps.com/', operations: ['invoices', 'customers', 'accounts', 'transactions'], status: 'planned', webhookSupport: true },
  { id: 'salesforce', name: 'Salesforce', category: 'crm', description: 'Leads, accounts, opportunities, contacts, campaigns', authMethod: 'oauth2', apiBaseUrl: 'https://{instance}.salesforce.com', docsUrl: 'https://developer.salesforce.com/', operations: ['accounts', 'contacts', 'leads', 'opportunities', 'campaigns'], status: 'production', webhookSupport: true },
  { id: 'hubspot', name: 'HubSpot', category: 'crm', description: 'CRM, marketing, sales, service hub, content management', authMethod: 'oauth2', apiBaseUrl: 'https://api.hubapi.com', docsUrl: 'https://developers.hubspot.com/', operations: ['contacts', 'companies', 'deals', 'tickets', 'workflows'], status: 'production', webhookSupport: true },
  { id: 'zoho-crm', name: 'Zoho CRM', category: 'crm', description: 'Leads, deals, contacts, accounts, campaigns, analytics', authMethod: 'oauth2', apiBaseUrl: 'https://www.zohoapis.com/crm/v5', docsUrl: 'https://www.zoho.com/crm/developer/', operations: ['leads', 'contacts', 'accounts', 'deals', 'campaigns'], status: 'planned', webhookSupport: true },
  { id: 'microsoft-dynamics-crm', name: 'Microsoft Dynamics CRM', category: 'crm', description: 'Sales — leads, opportunities, accounts, forecasting', authMethod: 'oauth2', apiBaseUrl: 'https://{org}.api.crm.dynamics.com', docsUrl: 'https://learn.microsoft.com/en-us/dynamics365/sales/', operations: ['leads', 'opportunities', 'accounts', 'contacts', 'activities'], status: 'planned', webhookSupport: true },
  { id: 'pipedrive', name: 'Pipedrive', category: 'crm', description: 'Deals, leads, persons, organizations, activities, pipelines', authMethod: 'api-key', apiBaseUrl: 'https://api.pipedrive.com/v1', docsUrl: 'https://developers.pipedrive.com/', operations: ['deals', 'leads', 'persons', 'organizations', 'pipelines'], status: 'planned', webhookSupport: true },
  { id: 'wex', name: 'WEX', category: 'fuel-fleet', description: 'Fleet fuel cards, transaction data, spending controls', authMethod: 'oauth2', apiBaseUrl: 'https://api.wexinc.com', docsUrl: 'https://www.wexinc.com/', operations: ['transactions', 'cards', 'drivers', 'spending-limits'], status: 'planned', webhookSupport: true },
  { id: 'comdata', name: 'Comdata', category: 'fuel-fleet', description: 'Fleet fuel cards, virtual cards, payroll, spend management', authMethod: 'api-key', apiBaseUrl: 'https://api.comdata.com', docsUrl: 'https://www.comdata.com/', operations: ['transactions', 'cards', 'limits', 'drivers'], status: 'planned', webhookSupport: false },
  { id: 'fuelman', name: 'Fuelman', category: 'fuel-fleet', description: 'Fleet fuel cards, purchase controls, analytics', authMethod: 'api-key', apiBaseUrl: 'https://api.fuelman.com', docsUrl: 'https://www.fuelman.com/', operations: ['transactions', 'cards', 'drivers', 'alerts'], status: 'planned', webhookSupport: false },
  { id: 'efs', name: 'EFS', category: 'fuel-fleet', description: 'Over-the-road fleet fuel cards, factoring, settlement', authMethod: 'api-key', apiBaseUrl: 'https://api.efsllc.com', docsUrl: 'https://www.efsllc.com/', operations: ['transactions', 'cards', 'settlement', 'factoring'], status: 'planned', webhookSupport: false },
  { id: 'motive-eld', name: 'Motive (Keep Truckin)', category: 'eld', description: 'ELD, DVIR, IFTA, GPS, dashcam, dispatch', authMethod: 'oauth2', apiBaseUrl: 'https://api.gomotive.com/v1', docsUrl: 'https://developer.gomotive.com/', operations: ['hos-logs', 'dvir', 'vehicles', 'drivers', 'ifta'], status: 'planned', webhookSupport: true },
  { id: 'samsara-eld', name: 'Samsara ELD', category: 'eld', description: 'HOS compliance, DVIR, driver app, IFTA reporting', authMethod: 'bearer', apiBaseUrl: 'https://api.samsara.com', docsUrl: 'https://developers.samsara.com/', operations: ['hos-clocks', 'hos-logs', 'dvir', 'vehicles'], status: 'production', webhookSupport: true },
  { id: 'geotab-drive', name: 'Geotab Drive', category: 'eld', description: 'ELD compliance, HOS, DVIR, driver workflows', authMethod: 'basic', apiBaseUrl: 'https://my.geotab.com/apiv1', docsUrl: 'https://geotab.github.io/sdk/', operations: ['duty-status-logs', 'dvir', 'driver-change'], status: 'production', webhookSupport: true },
  { id: 'omnitracs-eld', name: 'Omnitracs ELD', category: 'eld', description: 'FMCSA-compliant logging, HOS, driver workflow', authMethod: 'oauth2', apiBaseUrl: 'https://api.omnitracs.com', docsUrl: 'https://www.omnitracs.com/', operations: ['hos-logs', 'dvir', 'drivers', 'violations'], status: 'planned', webhookSupport: true },
  { id: 'azuga-eld', name: 'Azuga ELD', category: 'eld', description: 'HOS, DVIR, driver app, IFTA, compliance alerts', authMethod: 'api-key', apiBaseUrl: 'https://api.azuga.com/v2', docsUrl: 'https://www.azuga.com/', operations: ['hos-logs', 'dvir', 'drivers', 'violations'], status: 'planned', webhookSupport: false },
  { id: 'dat-load-board', name: 'DAT Load Board', category: 'freight', description: 'Largest freight marketplace, load/truck matching, rate analytics', authMethod: 'oauth2', apiBaseUrl: 'https://freight.api.dat.com', docsUrl: 'https://developers.dat.com/', operations: ['search-loads', 'post-truck', 'rate-look', 'analytics'], status: 'planned', webhookSupport: true },
  { id: 'truckstop', name: 'Truckstop.com', category: 'freight', description: 'Load board, rate index, carrier monitoring, book-it-now', authMethod: 'api-key', apiBaseUrl: 'https://api.truckstop.com', docsUrl: 'https://developer.truckstop.com/', operations: ['loads', 'trucks', 'rates', 'carrier-monitoring'], status: 'planned', webhookSupport: true },
  { id: '123loadboard', name: '123Loadboard', category: 'freight', description: 'Load searching, truck posting, mileage calculator', authMethod: 'api-key', apiBaseUrl: 'https://api.123loadboard.com', docsUrl: 'https://www.123loadboard.com/', operations: ['loads', 'trucks', 'mileage', 'rates'], status: 'planned', webhookSupport: false },
  { id: 'direct-freight', name: 'Direct Freight', category: 'freight', description: 'Load board, truck posting, carrier tools, FMCSA data', authMethod: 'api-key', apiBaseUrl: 'https://api.directfreight.com', docsUrl: 'https://www.directfreight.com/', operations: ['loads', 'trucks', 'carrier-search'], status: 'planned', webhookSupport: false },
  { id: 'tableau', name: 'Tableau', category: 'analytics', description: 'Visual analytics, dashboards, data prep, embedded analytics', authMethod: 'jwt', apiBaseUrl: 'https://{server}/api/3.22', docsUrl: 'https://help.tableau.com/', operations: ['workbooks', 'views', 'datasources', 'embed'], status: 'planned', webhookSupport: true },
  { id: 'power-bi', name: 'Power BI', category: 'analytics', description: 'Reports, dashboards, datasets, dataflows, embedded', authMethod: 'oauth2', apiBaseUrl: 'https://api.powerbi.com/v1.0', docsUrl: 'https://learn.microsoft.com/en-us/rest/api/power-bi/', operations: ['reports', 'dashboards', 'datasets', 'refresh', 'embed'], status: 'planned', webhookSupport: false },
  { id: 'looker', name: 'Looker', category: 'analytics', description: 'Business intelligence, LookML modeling, embedded analytics', authMethod: 'oauth2', apiBaseUrl: 'https://{instance}.looker.com/api/4.0', docsUrl: 'https://cloud.google.com/looker/', operations: ['looks', 'dashboards', 'queries', 'embed'], status: 'planned', webhookSupport: false },
  { id: 'qlik', name: 'Qlik', category: 'analytics', description: 'Analytics, data integration, AI-powered insights', authMethod: 'jwt', apiBaseUrl: 'https://{tenant}.us.qlikcloud.com/api', docsUrl: 'https://qlik.dev/', operations: ['apps', 'spaces', 'data-files', 'embed'], status: 'planned', webhookSupport: true },
  { id: 'google-analytics', name: 'Google Analytics', category: 'analytics', description: 'GA4 — event tracking, audiences, conversions, reporting', authMethod: 'oauth2', apiBaseUrl: 'https://analyticsdata.googleapis.com/v1beta', docsUrl: 'https://developers.google.com/analytics/', operations: ['run-report', 'batch-report', 'realtime-report'], status: 'planned', webhookSupport: false },
  { id: 'docusign', name: 'DocuSign', category: 'e-signatures', description: 'eSignature — envelopes, templates, signing, CLM', authMethod: 'oauth2', apiBaseUrl: 'https://na4.docusign.net/restapi/v2.1', docsUrl: 'https://developers.docusign.com/', operations: ['create-envelope', 'send', 'status', 'templates'], status: 'planned', webhookSupport: true },
  { id: 'adobe-sign', name: 'Adobe Sign', category: 'e-signatures', description: 'Agreements, templates, workflows, mega-sign', authMethod: 'oauth2', apiBaseUrl: 'https://api.na4.adobesign.com/api/rest/v6', docsUrl: 'https://developer.adobe.com/', operations: ['agreements', 'templates', 'workflows', 'widgets'], status: 'planned', webhookSupport: true },
  { id: 'pandadoc', name: 'PandaDoc', category: 'e-signatures', description: 'Document automation, proposals, contracts, e-signatures', authMethod: 'oauth2', apiBaseUrl: 'https://api.pandadoc.com/public/v1', docsUrl: 'https://developers.pandadoc.com/', operations: ['documents', 'templates', 'contacts', 'send'], status: 'planned', webhookSupport: true },
  { id: 'hellosign', name: 'HelloSign', category: 'e-signatures', description: 'Dropbox Sign — signature requests, templates, embedded signing', authMethod: 'api-key', apiBaseUrl: 'https://api.hellosign.com/v3', docsUrl: 'https://developers.hellosign.com/', operations: ['signature-request', 'templates', 'embedded'], status: 'planned', webhookSupport: true },
  { id: 'solid-protocol', name: 'Solid Protocol', category: 'e-signatures', description: 'Decentralized data pods, identity, linked data', authMethod: 'oauth2', apiBaseUrl: 'https://solidcommunity.net', docsUrl: 'https://solidproject.org/', operations: ['read-resource', 'write-resource', 'acl'], status: 'planned', webhookSupport: true },
  { id: 'fedex', name: 'FedEx', category: 'shipping', description: 'Rate quotes, tracking, labels, pickup scheduling, address validation', authMethod: 'oauth2', apiBaseUrl: 'https://apis.fedex.com', docsUrl: 'https://developer.fedex.com/', operations: ['rates', 'ship', 'track', 'address-validation', 'pickup'], status: 'production', webhookSupport: true },
  { id: 'ups', name: 'UPS', category: 'shipping', description: 'Shipping, tracking, rates, address validation, time-in-transit', authMethod: 'oauth2', apiBaseUrl: 'https://onlinetools.ups.com/api', docsUrl: 'https://developer.ups.com/', operations: ['rate', 'ship', 'track', 'address-validation', 'time-in-transit'], status: 'production', webhookSupport: true },
  { id: 'usps', name: 'USPS', category: 'shipping', description: 'Rates, tracking, labels, address verification, ZIP lookup', authMethod: 'api-key', apiBaseUrl: 'https://secure.shippingapis.com', docsUrl: 'https://www.usps.com/business/web-tools-apis/', operations: ['rate', 'track', 'verify-address', 'zip-lookup', 'label'], status: 'production', webhookSupport: false },
  { id: 'dhl', name: 'DHL', category: 'shipping', description: 'Express shipping, tracking, rates, pickup, address validation (global)', authMethod: 'basic', apiBaseUrl: 'https://express.api.dhl.com/mydhlapi', docsUrl: 'https://developer.dhl.com/', operations: ['rates', 'shipments', 'tracking', 'pickup', 'address-validation'], status: 'production', webhookSupport: true },
  { id: 'shipstation', name: 'ShipStation', category: 'shipping', description: 'Multi-carrier shipping, label creation, order management', authMethod: 'basic', apiBaseUrl: 'https://ssapi.shipstation.com', docsUrl: 'https://www.shipstation.com/docs/api/', operations: ['orders', 'shipments', 'carriers', 'labels', 'rates'], status: 'production', webhookSupport: true },
  { id: 'easypost', name: 'EasyPost', category: 'shipping', description: 'Multi-carrier shipping API, rates, labels, tracking, insurance', authMethod: 'api-key', apiBaseUrl: 'https://api.easypost.com/v2', docsUrl: 'https://docs.easypost.com/', operations: ['shipments', 'rates', 'labels', 'tracking', 'insurance'], status: 'production', webhookSupport: true },
  { id: 'shippo', name: 'Shippo', category: 'shipping', description: 'Multi-carrier shipping, label generation, tracking, rates comparison', authMethod: 'bearer', apiBaseUrl: 'https://api.goshippo.com', docsUrl: 'https://goshippo.com/docs/', operations: ['shipments', 'rates', 'labels', 'tracking', 'addresses'], status: 'planned', webhookSupport: true },
  { id: 'doordash-drive', name: 'DoorDash Drive', category: 'last-mile', description: 'On-demand delivery, scheduled delivery, white-label', authMethod: 'jwt', apiBaseUrl: 'https://openapi.doordash.com/drive/v2', docsUrl: 'https://developer.doordash.com/', operations: ['create-delivery', 'get-delivery', 'cancel-delivery', 'quotes'], status: 'planned', webhookSupport: true },
  { id: 'uber-eats', name: 'Uber Eats', category: 'last-mile', description: 'Restaurant delivery, menu management, order management', authMethod: 'oauth2', apiBaseUrl: 'https://api.uber.com/v1', docsUrl: 'https://developer.uber.com/', operations: ['orders', 'menus', 'stores', 'delivery-status'], status: 'planned', webhookSupport: true },
  { id: 'grubhub', name: 'Grubhub', category: 'last-mile', description: 'Restaurant delivery, catering, order management API', authMethod: 'api-key', apiBaseUrl: 'https://api-gtm.grubhub.com', docsUrl: 'https://www.grubhub.com/', operations: ['orders', 'restaurants', 'menus', 'delivery'], status: 'planned', webhookSupport: true },
  { id: 'toast-pos', name: 'Toast POS', category: 'pos-restaurant', description: 'Restaurant POS, online ordering, delivery, kitchen display', authMethod: 'oauth2', apiBaseUrl: 'https://api.toasttab.com', docsUrl: 'https://doc.toasttab.com/', operations: ['orders', 'menus', 'restaurants', 'labor', 'payments'], status: 'planned', webhookSupport: true },
  { id: 'square-for-restaurants', name: 'Square for Restaurants', category: 'pos-restaurant', description: 'POS, kitchen display, online ordering, team management', authMethod: 'oauth2', apiBaseUrl: 'https://connect.squareup.com/v2', docsUrl: 'https://developer.squareup.com/', operations: ['orders', 'catalog', 'team-members', 'locations'], status: 'planned', webhookSupport: true },
  { id: 'cerner', name: 'Cerner', category: 'healthcare', description: 'Oracle Health — EHR, patient data, scheduling, FHIR R4', authMethod: 'oauth2', apiBaseUrl: 'https://fhir-open.cerner.com/r4', docsUrl: 'https://fhir.cerner.com/', operations: ['patients', 'encounters', 'observations', 'appointments'], status: 'planned', webhookSupport: false },
  { id: 'allscripts', name: 'Allscripts', category: 'healthcare', description: 'EHR, practice management, RCM, patient engagement', authMethod: 'oauth2', apiBaseUrl: 'https://open.allscripts.com/fhir', docsUrl: 'https://developer.allscripts.com/', operations: ['patients', 'encounters', 'medications', 'scheduling'], status: 'planned', webhookSupport: false },
  { id: 'epic', name: 'Epic', category: 'healthcare', description: 'EHR integration via FHIR R4, patient access, care team workflows', authMethod: 'oauth2', apiBaseUrl: 'https://fhir.epic.com', docsUrl: 'https://fhir.epic.com/', operations: ['patients', 'encounters', 'observations', 'conditions'], status: 'planned', webhookSupport: false },
  { id: 'hl7-fhir', name: 'HL7 FHIR', category: 'healthcare', description: 'Universal healthcare interop standard, FHIR R4 resources', authMethod: 'bearer', apiBaseUrl: 'https://hapi.fhir.org/baseR4', docsUrl: 'https://hl7.org/fhir/', operations: ['patient', 'observation', 'condition', 'medication-request'], status: 'planned', webhookSupport: false },
  { id: 'servicetitan', name: 'ServiceTitan', category: 'field-service', description: 'Field service management, dispatching, estimating, payments', authMethod: 'oauth2', apiBaseUrl: 'https://api.servicetitan.io', docsUrl: 'https://developer.servicetitan.io/', operations: ['jobs', 'customers', 'technicians', 'invoices', 'dispatch'], status: 'planned', webhookSupport: true },
  { id: 'jobber', name: 'Jobber', category: 'field-service', description: 'Field service scheduling, quoting, invoicing, client hub', authMethod: 'oauth2', apiBaseUrl: 'https://api.getjobber.com/api/graphql', docsUrl: 'https://developer.getjobber.com/', operations: ['jobs', 'clients', 'quotes', 'invoices', 'schedules'], status: 'planned', webhookSupport: true },
  { id: 'housecall-pro', name: 'Housecall Pro', category: 'field-service', description: 'Home service management, scheduling, dispatching, payments', authMethod: 'oauth2', apiBaseUrl: 'https://api.housecallpro.com', docsUrl: 'https://docs.housecallpro.com/', operations: ['jobs', 'customers', 'estimates', 'invoices', 'dispatching'], status: 'planned', webhookSupport: true },
  { id: 'fieldedge', name: 'FieldEdge', category: 'field-service', description: 'HVAC/plumbing/electrical field service, dispatching, flat-rate pricing', authMethod: 'api-key', apiBaseUrl: 'https://api.fieldedge.com', docsUrl: 'https://www.fieldedge.com/', operations: ['work-orders', 'customers', 'technicians', 'invoices'], status: 'planned', webhookSupport: true },
] as const;


export class IntegrationRegistry {
  private readonly providers: ReadonlyMap<string, IntegrationProvider>;

  constructor() {
    this.providers = new Map(ALL_PROVIDERS.map((p) => [p.id, p]));
  }

  getProvider(id: string): IntegrationProvider | undefined {
    return this.providers.get(id);
  }

  getByCategory(category: IntegrationCategory): IntegrationProvider[] {
    return ALL_PROVIDERS.filter((p) => p.category === category);
  }

  getByStatus(status: AdapterStatus): IntegrationProvider[] {
    return ALL_PROVIDERS.filter((p) => p.status === status);
  }

  getProduction(): IntegrationProvider[] {
    return this.getByStatus('production');
  }

  search(query: string): IntegrationProvider[] {
    const q = query.toLowerCase();
    return ALL_PROVIDERS.filter(
      (p) =>
        p.name.toLowerCase().includes(q) ||
        p.description.toLowerCase().includes(q) ||
        p.category.includes(q) ||
        p.operations.some((op) => op.includes(q))
    );
  }

  get totalCount(): number { return ALL_PROVIDERS.length; }

  get productionCount(): number {
    return ALL_PROVIDERS.filter((p) => p.status === 'production').length;
  }

  getCategorySummary(): Record<string, number> {
    const summary: Record<string, number> = {};
    for (const p of ALL_PROVIDERS) {
      summary[p.category] = (summary[p.category] ?? 0) + 1;
    }
    return summary;
  }
}

export const integrationRegistry = new IntegrationRegistry();
