#!/usr/bin/env bash
# Runs ON the Hetzner VM. Executed via `ssh Hetzner_Server 'bash -s' < dogfood.sh`.
# Expects a tarball at /tmp/bench-packages.tgz staged by cycle.sh.
set -euo pipefail

SANDBOX_DIR="/opt/bench-sandbox"
WORKSPACE_DIR="${SANDBOX_DIR}/workspace"
INSTALL_DIR="${SANDBOX_DIR}/demo"
TARBALL="/tmp/bench-packages.tgz"

RED=$'\033[31m'
GREEN=$'\033[32m'
YELLOW=$'\033[33m'
BOLD=$'\033[1m'
DIM=$'\033[2m'
NC=$'\033[0m'

step() { printf "${BOLD}→${NC} %s\n" "$1"; }
ok()   { printf "${GREEN}✓${NC} %s\n" "$1"; }
warn() { printf "${YELLOW}⚠${NC} %s\n" "$1"; }
fail() { printf "${RED}✗${NC} %s\n" "$1"; FAILED=1; }

FAILED=0

# ── Preflight ───────────────────────────────────────────────────────────────

step "preflight: tooling"
command -v docker >/dev/null || { fail "docker missing"; exit 2; }
docker compose version >/dev/null 2>&1 || { fail "docker compose plugin missing"; exit 2; }
command -v node >/dev/null || { fail "node missing"; exit 2; }
command -v pnpm >/dev/null || { fail "pnpm missing"; exit 2; }
[ -f "$TARBALL" ] || { fail "tarball missing at $TARBALL — run cycle.sh from project root"; exit 2; }
ok "tooling: $(docker --version) | node $(node --version) | pnpm $(pnpm --version)"

# ── Extract ─────────────────────────────────────────────────────────────────

step "extract bench packages"
mkdir -p "$WORKSPACE_DIR"
cd "$WORKSPACE_DIR"
# Preserve node_modules across cycles for fast re-install
find . -maxdepth 1 -mindepth 1 \
  ! -name 'node_modules' \
  ! -name '.pnpm-store' \
  -exec rm -rf {} +
tar -xzf "$TARBALL"
ok "extracted → $WORKSPACE_DIR"

# ── Install ─────────────────────────────────────────────────────────────────

step "pnpm install (incremental)"
cd "$WORKSPACE_DIR"
pnpm install --prefer-offline --no-frozen-lockfile --silent 2>&1 | tail -5 || {
  fail "pnpm install"
  exit 3
}
ok "dependencies installed"

# ── Locate bench CLI ────────────────────────────────────────────────────────

step "locate bench CLI (source via tsx)"
TSX_REL=$(find node_modules/.pnpm -path '*/tsx@*/node_modules/tsx/dist/cli.mjs' -type f 2>/dev/null | head -1)
[ -n "$TSX_REL" ] || { fail "tsx not installed"; exit 3; }
TSX_CLI="$WORKSPACE_DIR/$TSX_REL"
BENCH_ENTRY="$WORKSPACE_DIR/packages/bench-cli/src/index.ts"
[ -f "$BENCH_ENTRY" ] || { fail "bench CLI entry missing at $BENCH_ENTRY"; exit 3; }
BENCH="node $TSX_CLI $BENCH_ENTRY"
ok "bench ready"

# ── Exercise: init ──────────────────────────────────────────────────────────

step "bench init demo"
rm -rf "$INSTALL_DIR"
cd "$SANDBOX_DIR"
if $BENCH init "$INSTALL_DIR" 2>&1; then
  ok "init"
else
  fail "init failed"
fi

# ── Exercise: doctor ────────────────────────────────────────────────────────

step "bench doctor"
cd "$INSTALL_DIR"
if $BENCH doctor 2>&1; then
  ok "doctor"
else
  # doctor exit=2 is preflight failure — capture but don't bail
  warn "doctor returned non-zero (expected until BENCH_SERVICE_TOKEN is generated by init)"
fi

# ── Exercise: deploy --dry-run ──────────────────────────────────────────────

step "bench --dry-run deploy"
if $BENCH --dry-run deploy 2>&1; then
  ok "dry-run deploy"
else
  fail "dry-run deploy failed"
fi

# ── Exercise: real deploy (expected to fail on image pull for now) ──────────

step "bench deploy (real — will surface image-pull issue until registry publishes)"
DEPLOY_OUT=$(mktemp)
if $BENCH deploy >"$DEPLOY_OUT" 2>&1; then
  ok "real deploy — ALL IMAGES RESOLVED"

  step "bench status"
  if $BENCH status 2>&1; then
    ok "status"
  else
    fail "status"
  fi
else
  warn "real deploy failed — dumping last 30 lines:"
  printf "${DIM}"
  tail -30 "$DEPLOY_OUT"
  printf "${NC}"
  warn "expected failure until ghcr.io/wityliti/witylogix-* images are published"
fi
rm -f "$DEPLOY_OUT"

# ── Exercise: stub Phase 1b commands (report not-yet-implemented cleanly) ──

for cmd in migrate new-tenant backup restore; do
  step "bench $cmd (should report not-yet-implemented until the task lands)"
  $BENCH "$cmd" ${cmd:+$([ "$cmd" = new-tenant ] && echo acme-test || echo)} 2>&1 | tail -3 || true
done

# ── Summary ─────────────────────────────────────────────────────────────────

printf "\n${BOLD}─ summary ─${NC}\n"
if [ "$FAILED" -eq 0 ]; then
  ok "cycle completed — no blocking failures"
  exit 0
else
  fail "cycle completed with $FAILED failure(s)"
  exit 1
fi
