/**
 * ELD (Electronic Logging Device) Adapters — Core type definitions.
 *
 * Defines unified types and interfaces for all ELD integrations:
 * Motive, Omnitracs, Azuga. Implements FMCSA Part 395 HOS compliance rules.
 *
 * - Driver logs, duty status transitions, violations
 * - Vehicle tracking and diagnostics
 * - DVIR (Driver Vehicle Inspection Report) submissions
 * - HOS (Hours of Service) calculation and compliance
 * - Webhook events for real-time updates
 */

// ─── Duty Status Types ──────────────────────────────────────

/** FMCSA Part 395 duty status values */
export type DutyStatus =
  | "driving"
  | "on-duty"
  | "sleeper-berth"
  | "off-duty"
  | "personal-conveyance"
  | "yard-move";

/** Violation type for HOS compliance */
export type ViolationType =
  | "hours-14"
  | "hours-11"
  | "hours-8"
  | "hours-60-70"
  | "break-30min";

/** ELD event type */
export type ELDEventType =
  | "duty-status-change"
  | "location-update"
  | "hos-violation"
  | "dvir-submitted"
  | "fault-code"
  | "diagnostic-event"
  | "driver-cert"
  | "vehicle-cert";

// ─── Driver Log ─────────────────────────────────────────────

/**
 * Standardized driver log record representing a continuous duty period.
 * Normalizes across Motive, Omnitracs, Azuga APIs.
 */
export interface ELDDriverLog {
  /** Unique log ID (generated by ELD provider) */
  id: string;

  /** Tenant/account ID */
  accountId: string;

  /** Driver ID from ELD provider */
  driverId: string;

  /** Vehicle ID from ELD provider */
  vehicleId: string;

  /** Start time of this duty period (ISO 8601) */
  startTime: Date;

  /** End time of this duty period (ISO 8601) */
  endTime: Date;

  /** Duty status during this period */
  dutyStatus: DutyStatus;

  /** Total miles driven (if driving status) */
  miles?: number;

  /** Total hours in this duty period */
  hours: number;

  /** Location details at log start */
  startLocation?: {
    latitude: number;
    longitude: number;
    address?: string;
    city?: string;
    state?: string;
  };

  /** Location details at log end */
  endLocation?: {
    latitude: number;
    longitude: number;
    address?: string;
    city?: string;
    state?: string;
  };

  /** Notes/remarks from driver or ELD */
  remarks?: string;

  /** Sequence number for ordering within a day */
  sequence: number;

  /** Whether this log was edited post-submission */
  edited: boolean;

  /** Timestamp when log was created/submitted */
  createdAt: Date;

  /** Timestamp when log was last updated */
  updatedAt: Date;
}

// ─── Duty Status Record ─────────────────────────────────────

/**
 * Represents a single duty status change event.
 */
export interface ELDDutyStatus {
  /** Unique event ID */
  id: string;

  /** Account ID */
  accountId: string;

  /** Driver ID */
  driverId: string;

  /** Vehicle ID (if applicable) */
  vehicleId?: string;

  /** The new duty status */
  status: DutyStatus;

  /** When the status change occurred */
  changedAt: Date;

  /** Location when status changed */
  location?: {
    latitude: number;
    longitude: number;
    address?: string;
  };

  /** Hours of service available for driving (calculated) */
  availableHoursDriving: number;

  /** Hours of service available on-duty (calculated) */
  availableHoursOnDuty: number;

  /** Timestamp of record creation */
  createdAt: Date;
}

// ─── HOS Violation ──────────────────────────────────────────

/**
 * Represents a detected FMCSA Part 395 HOS violation.
 */
export interface ELDViolation {
  /** Unique violation ID */
  id: string;

  /** Account ID */
  accountId: string;

  /** Driver ID */
  driverId: string;

  /** Vehicle ID (if applicable) */
  vehicleId?: string;

  /** Type of violation */
  violationType: ViolationType;

  /** Human-readable description */
  description: string;

  /** Severity level */
  severity: "warning" | "error" | "critical";

  /** When violation was detected */
  detectedAt: Date;

  /** Time range during which violation occurred */
  violationTimeRange: {
    start: Date;
    end: Date;
  };

  /** Relevant HOS hours at time of violation */
  hosContext: {
    /** Hours driven in 11-hour period */
    hours11?: number;
    /** Hours driven in 14-hour period */
    hours14?: number;
    /** Hours driven in 60-hour period (8 days) */
    hours60?: number;
    /** Hours driven in 70-hour period (8 days) */
    hours70?: number;
    /** Minutes since last 30-minute break */
    minutesSinceBreak?: number;
  };

  /** Whether violation has been acknowledged by driver */
  acknowledged: boolean;

  /** When driver acknowledged (if applicable) */
  acknowledgedAt?: Date;

  /** Timestamp of record creation */
  createdAt: Date;
}

// ─── Vehicle ────────────────────────────────────────────────

/**
 * Standardized vehicle record from ELD provider.
 */
export interface ELDVehicle {
  /** Unique vehicle ID from ELD provider */
  id: string;

  /** Account ID */
  accountId: string;

  /** VIN */
  vin: string;

  /** License plate */
  licensePlate: string;

  /** Make and model */
  make?: string;

  model?: string;

  /** Year */
  year?: number;

  /** Vehicle group/fleet assignment */
  group?: string;

  /** Current odometer reading (miles) */
  odometerMiles?: number;

  /** Fuel type */
  fuelType?: "diesel" | "gasoline" | "electric" | "hybrid";

  /** Capacity (GVWR in lbs) */
  capacityLbs?: number;

  /** Current GPS location */
  currentLocation?: {
    latitude: number;
    longitude: number;
    address?: string;
    updatedAt: Date;
  };

  /** Whether vehicle is currently assigned to a driver */
  driverId?: string;

  /** Active faults/trouble codes */
  activeFaults: string[];

  /** Last inspection date */
  lastInspectionDate?: Date;

  /** Next inspection due date */
  nextInspectionDueDate?: Date;

  /** Maintenance records status */
  maintenanceStatus?: "good" | "pending" | "overdue";

  /** Timestamp of record creation */
  createdAt: Date;

  /** Timestamp of last update */
  updatedAt: Date;
}

// ─── DVIR (Driver Vehicle Inspection Report) ────────────────

/**
 * DVIR submission for vehicle condition documentation.
 * Required by FMCSA 49 CFR 396.11.
 */
export interface ELDDVIR {
  /** Unique DVIR ID */
  id: string;

  /** Account ID */
  accountId: string;

  /** Driver ID who submitted DVIR */
  driverId: string;

  /** Vehicle ID being inspected */
  vehicleId: string;

  /** Inspection time (ISO 8601) */
  inspectionTime: Date;

  /** Type of DVIR: pre-trip or post-trip */
  type: "pre-trip" | "post-trip";

  /** Overall condition: pass, defect, or not-safe */
  condition: "pass" | "defect" | "not-safe";

  /** List of defects found (empty if pass) */
  defects: Array<{
    /** Component or area with defect */
    component: string;
    /** Severity: minor, major, critical */
    severity: "minor" | "major" | "critical";
    /** Description of defect */
    description: string;
    /** Photos/evidence URLs */
    evidenceUrls?: string[];
  }>;

  /** Driver's remarks */
  driverRemarks?: string;

  /** Mechanic review/repair notes (post-submission) */
  mechanicRemarks?: string;

  /** Whether defects were corrected before next trip */
  defectsResolved?: boolean;

  /** Timestamp when DVIR was submitted */
  submittedAt: Date;

  /** Timestamp when last updated */
  updatedAt: Date;
}

// ─── ELD Event ──────────────────────────────────────────────

/**
 * Represents a significant event from an ELD provider.
 * Used for webhook processing and real-time updates.
 */
export interface ELDEvent {
  /** Unique event ID */
  id: string;

  /** Event type */
  type: ELDEventType;

  /** Account ID */
  accountId: string;

  /** Driver ID (when applicable) */
  driverId?: string;

  /** Vehicle ID (when applicable) */
  vehicleId?: string;

  /** Event timestamp */
  timestamp: Date;

  /** Event-specific data payload */
  data: Record<string, unknown>;

  /** Whether event has been processed */
  processed: boolean;

  /** Processing timestamp (if processed) */
  processedAt?: Date;

  /** Record creation timestamp */
  createdAt: Date;
}

// ─── ELD Provider Configuration ──────────────────────────────

/**
 * Configuration for ELD provider integration.
 * Tenant-specific settings and authentication.
 */
export interface ELDConfig {
  /** ELD provider type: motive, omnitracs, or azuga */
  provider: "motive" | "omnitracs" | "azuga";

  /** API key (varies by provider) */
  apiKey?: string;

  /** API secret (for HMAC-authenticated providers) */
  apiSecret?: string;

  /** OAuth2 access token */
  accessToken?: string;

  /** OAuth2 refresh token (if applicable) */
  refreshToken?: string;

  /** OAuth2 token expiry (ISO 8601) */
  tokenExpiresAt?: Date;

  /** Base URL override for development/staging */
  baseUrl?: string;

  /** Account/organization ID from provider */
  accountId?: string;

  /** Whether to auto-sync logs and statuses */
  autoSync: boolean;

  /** Sync interval in minutes (default: 60) */
  syncIntervalMinutes?: number;

  /** Whether to enable webhook processing */
  enableWebhooks: boolean;

  /** Webhook secret for signature verification */
  webhookSecret?: string;

  /** Provider-specific configuration */
  providerConfig?: Record<string, unknown>;

  /** Timestamp of configuration creation */
  createdAt: Date;

  /** Timestamp of last update */
  updatedAt: Date;
}

// ─── Webhook Event ──────────────────────────────────────────

/**
 * Webhook event payload from ELD provider.
 */
export interface ELDWebhookEvent {
  /** Event ID from provider */
  id: string;

  /** Event type */
  type: ELDEventType;

  /** Account ID */
  accountId: string;

  /** Timestamp of event */
  timestamp: Date;

  /** Event payload (provider-specific) */
  payload: Record<string, unknown>;

  /** Webhook signature for verification */
  signature?: string;
}

// ─── Adapter Interface ──────────────────────────────────────

/**
 * Interface that all ELD adapters must implement.
 */
export interface ELDAdapterInterface {
  /** Initialize/authenticate with provider */
  initialize(): Promise<void>;

  /** Get driver logs for a date range */
  getDriverLogs(
    driverId: string,
    startDate: Date,
    endDate: Date
  ): Promise<ELDDriverLog[]>;

  /** Get current duty status for driver */
  getDutyStatus(driverId: string): Promise<ELDDutyStatus>;

  /** Change driver duty status */
  setDutyStatus(
    driverId: string,
    status: DutyStatus,
    location?: { latitude: number; longitude: number }
  ): Promise<ELDDutyStatus>;

  /** Get HOS violations for driver */
  getViolations(driverId: string, days?: number): Promise<ELDViolation[]>;

  /** Get vehicle information */
  getVehicle(vehicleId: string): Promise<ELDVehicle>;

  /** Get list of all vehicles */
  getVehicles(): Promise<ELDVehicle[]>;

  /** Submit DVIR */
  submitDVIR(dvir: Partial<ELDDVIR>): Promise<ELDDVIR>;

  /** Get DVIR records */
  getDVIRs(vehicleId: string, days?: number): Promise<ELDDVIR[]>;

  /** Calculate HOS summary for driver */
  getHOSSummary(
    driverId: string,
    date: Date
  ): Promise<{
    hours11: number;
    hours14: number;
    hours60: number;
    hours70: number;
    availableDriving: number;
    availableOnDuty: number;
  }>;

  /** Handle incoming webhook event */
  handleWebhook(event: ELDWebhookEvent): Promise<void>;

  /** Health check */
  healthCheck(): Promise<boolean>;
}

// ─── HOS Calculation Types ──────────────────────────────────

/**
 * Hours of Service summary for compliance tracking.
 */
export interface HOSSummary {
  driverId: string;
  date: Date;
  hours11: number;
  hours14: number;
  hours60: number;
  hours70: number;
  availableDriving: number;
  availableOnDuty: number;
  violations: ViolationType[];
}

/**
 * Daily HOS record for aggregation.
 */
export interface HOSDailyRecord {
  driverId: string;
  date: Date;
  drivingHours: number;
  onDutyHours: number;
  sleeperHours: number;
  offDutyHours: number;
  personalConveyanceHours: number;
  yardMoveHours: number;
}

/**
 * 8-day HOS window for 60/70 hour rules.
 */
export interface HOS8DayWindow {
  driverId: string;
  startDate: Date;
  endDate: Date;
  hours60: number;
  hours70: number;
}
