apiVersion: v1
kind: Service
metadata:
  name: customer-portal
  labels:
    app.kubernetes.io/name: customer-portal
    app.kubernetes.io/part-of: witylogix
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: customer-portal
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
