[build]
builder = "dockerfile"
dockerfilePath = "../../Dockerfile.api"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 10
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[service]
internalPort = 3000
