[build]
builder = "dockerfile"
dockerfilePath = "../../Dockerfile.tracking-page"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 10
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[service]
internalPort = 3000
